package.json
webpack.config.js

Updates the webpack config to put the compiled bundle in `./build/public` rather than the developer's `/dist` directory.
We still need to do more to get CI working:
1. ~~Fix `npm run build`.~~
2. ~~Fix `npm run test`.~~ In an ideal world it would also run tests.

Don't require superuser access for development.

---

docker/tiller/templates/askdarcel-web.erb

When using a regex location with a match variable, nginx doesn't pass these through automatically.

Include query parameters when proxying to the API.

---

app/components/Resources/ResourcesTable.js
package.json

The page at URL /resources?query=:query will display resource search results for the query :query. This change does _not_ wire up the search input fields on the front page or in the header.
The change also replaces tabs with spaces in `ResourcesTable.js`, which makes the change a bit hard to review. I'll point out where the functional changes were made.
Towards #43

Add search support to resource result page.

---

app/components/Resources/ResourcesTable.js

We use the first service's description instead.

Improve search result descriptions for null resource descriptions.

---

app/components/App.js
app/styles/components/_navigation.scss

Fixes #138.
The nav bar was being explicitly hidden on phone-sized screens, but this caused the page to look weird on the search results page. I changed it so that it'll still be displayed on phones, but
I kept the navigation search bar hidden, since it won't fit. I also changed the main App component to always render the page with the `<Navigation />` component and the `.container` wrapper, even on the root page, since without the `.container` wrapper the top of the hero banner was getting covered by the nav.
This technically ends up double-rendering the Navigation bar on the home page, but the version without the search bar is displayed on top, so it still looks correct, but we probably want to fix that later.
Here are some screenshots of what it looks like now on Desktop Chrome using …

Show navigation, even on phone-sized screens.

---

app/components/Admin/ChangeRequest.js

The reason phone numbers weren't displaying in the admin change requests page was because the switch statement that figures out how to pull out the original field value is missing a case for PhoneChangeRequests. This adds it to the list so that the phone number displays properly.
I also noticed that there was a minor typo in the AddressChangeRequest case, too, that I also fixed.
Lastly, I noticed that there's one more change request type that we're missing, the NoteChangeRequest. I didn't add it here, since there's currently no way to even submit a change request for a note, but I can create a new ticket to remind us to add it.

Add handler for PhoneChangeRequests. Fix handler for AddressChangeRequests

---

app/components/Edit/EditAddress.js

There was a typo in the change request submission form. After fixing this, I tested that I could update the zip code of a resource locally.

Fix posta_code typo.

---

app/components/Search/ResourcesMap.js
app/components/Search/ResourcesTable.js
app/routes.jsx
app/styles/components/_edit.scss
app/styles/components/_org-table.scss
app/styles/utils/_layout.scss
app/styles/utils/_reset.scss

This might require testing across multiple browsers to ensure that no regressions have slipped through. There was a bit of a domino effect where changing one thing had many other undesirable effects, but I think I stomped them all out.
Several styles were preventing scrollbars from displaying:
- it looks like we had some webkit-specific styles to explicitly hide the scrollbars by making them have 0 width and be transparent
- the #root element had a height of 100vh set, which meant that it could never be larger than the viewport
- the body and html elements had `position: fixed` set, which prevents scrollbars from appearing
I undid all of those and it now allows scrollbars to appear.
Basically, originally the `<html>` element had a height that was fixed to the viewport height, which …

Add scrollbars back

---

app/components/Admin/ChangeRequests.js
app/styles/components/_admin.scss

**Important note**: This was branched from #216, so don't merge until that's merge. See below more details.
This makes it so that change requests are collapsed per resource on the Admin approval page.
I've added a little chevron as a UI indicator that the object can be expanded, and the whole `<h1>` tag is clickable to make it easier to expand. Everything starts out collapsed by default.
On a technical note, I based this branch on @twolfe2's #216 branch, since I noticed he had re-indented a lot of the files there, and I wanted to minimize the merge conflicts, especially because I'm going to be out of town this weekend. Therefore, you should use https://github.com/ShelterTechSF/askdarcel-web/compare/admin-page-edit-ability...198-group-change-requests?w=1 to see the actual diff of the …

Collapse change request groups in Admin approval page

---

app/components/Edit/EditSchedule.js
app/utils/index.js

As @twolfe2 suspected in #236, we're not passing correctly formatted time values into `<input type="time">` fields. We were passing in things that looked like `7:00 PM`, but what it actually wants is `19:00`.
I added a new helper function, `timeToTimeInputValue()`, which takes our API's "concatenated hour-minute" format (e.g. `1900`) and formats it correctly.
An orthogonal problem that I noticed is that the edit page isn't correctly displaying schedules. The edit pages currently has one field per day, but we can have multiple time ranges per day. What we really need is to have multiple fields per day, and to also allow a user to add more time ranges, but I think that's outside the scope of this PR.

Use the correct format for time inputs.

---

app/components/Edit/EditCollection.js
app/components/Edit/EditPhones.js

This PR disables the "Add" button for phone numbers, since we actually haven't even implemented the code path for handling adding new phone numbers: https://github.com/ShelterTechSF/askdarcel-web/blob/c090b215dfc7e8ccf74b73dc7d49b6f7d732b864/app/components/Edit/EditSections.js#L152
See https://github.com/ShelterTechSF/askdarcel-api/issues/172 for what I think we need in general in order to create change requests that represent new database model instances that should get created, as opposed to change requests that only edit existing model instances.

Disable the add button for phone numbers

---

package.json
webpack.config.js

This is just a small change to upgrade webpack to 2.6, which is the last of the 2.x line. I wasn't able to upgrade it to 3.0 because some of our other dependencies claim that they depend on `^2.x.x`, and I didn't want to go and actually verify whether or not they work yet. We may want to upgrade some other packages to their latest available versions so that we can more easily upgrade webpack or other dependencies in the future.

Upgrade to webpack 2.6.

---

.eslintignore
app/components/Edit/EditPhones.js
app/components/Edit/EditSections.js
app/components/Resource/Resource.js
app/components/Resource/ResourceInfos.js
app/styles/components/_edit.scss

Depends on https://github.com/ShelterTechSF/askdarcel-api/pull/180
I added a new API endpoint for adding new phone numbers on the edit page. I also noticed that the `service_type` of the phone number wasn't hooked up, so I added it in both the display and edit views. One thing of note is that the linksf data appears to have put phone number extensions in the `service_type` field for many numbers. This will at least have the side effect of displaying them and making them editable, but we should probably be putting the extensions into the number field.
I attempted to lint the files that I edited here, but that's proving to be quite the endeavor because of how long the EditSections.js and ResourceInfos.js files are. I'm going to try to add linting on top of this, but if I don't get to that …

Enable adding multiple phones; also display and make editable phone service_type.

---

app/components/Edit/EditServices.js

There's currently no label for the add new service categories dropdown, so this adds one.

Add a label to the categories dropdown.

---

app/components/Edit/EditSections.js

While I was refactoring the Edit page in order to pass the linter, I accidentally introduced this bug, which prevents us from editing any nested collection items on Resource. Previously our `getDiffObject()`  method returned an object that looked like `{obj: {diffs go here}, numKeys: 10}`. I refactored it to just have the `obj` as the top level object, since the number of keys can be directly gotten from that instead of having to create a separate property. I forgot to change where we use the results of `getDiffObject()` to not try to get `diffObj.obj` anymore.
Tested that this does allow me to edit existing phone numbers, but I discovered another bug with the admin page not showing the phone number edits.

Remove unnecessary .obj on diff objects.

---

tools/cli/approveChangeRequests.js

I either tested it against an old version of the API, or I'm stupid and didn't do thorough enough QA. Either way, the body of my change_requests/:id/approve function was not actually updating the values.

Updated approveChangeRequests cli to correctly update fields

---

.eslintignore
app/components/Resource/DetailedHours.js
app/components/Search/ResourcesRow.jsx
package.json

**Issue 1:**The logic for displaying whether or not a resource is open was flawed and in order to fix it I brought in a third party time library, moment.js. 
**Issue 2:** Some of the days in our data had open/close times that were `null`. In order to clean up the UI, any day that has an open or close time that is `null` will not be displayed. The main reason we get nulls is because any open/close time left empty in the edit pages will update the data to be `null`.
Fixes #286

Fixed the logic for displaying open/close times in search results and made it so null times don't display

---

app/components/Edit/EditServices.js

Fixes Issue #288 
Show dropdown component in edit mode instead of rendering category list.
Not sure if this resulted in a correct change request since my admin UI isn't loading

Allow category editing for existing services

---

.eslintignore
app/components/Resource/Resource.js
app/styles/components/_org-page.scss

See https://github.com/ShelterTechSF/askdarcel-web/commit/764aed21d1c8c5e5032399090d17fb75e1684974 for a cleaner diff, since I linted `app/components/Resource/Resource.js`.
This adds a simple button to the resources page for verifying the resource's info. I didn't see any designs for it, so I just went with what I thought looked acceptable.
This actually makes an API request to the ChangeRequests route and creates a ChangeRequest that sets just the `verified_at` field. There wasn't an existing route on the server for directly setting the `verified_at` field, so if we want to allow users to verify resources without requiring an admin to approve it, we'll need to add an endpoint for that.

Add verification button

---

app/components/Resource/DetailedHours.js
app/utils/index.js

See cleaner, whitespace-agnostic diff here: https://github.com/ShelterTechSF/askdarcel-web/compare/295-do-not-treat-midnight-as-null?w=1
There was a minor bug in our time formatting helper functions where an `if (time)` would evaluate to false if the time is 0, since in JavaScript 0 is falsy. I fixed the comparisons to explicitly check for `if (time === null)`. This fixes the UI so that 0 is displayed as 12:00am instead of "null", and I also fixed the logic to filter out ScheduleDays that have 0 for either open or close times to filter out just nulls.

Do not treat 0 as an invalid time.

---

app/components/Edit/CategoriesDropdown.js

This fixes one of the issues described in #307, where the initial value of the CategoryDropdown was blank regardless of whether a service had existing categories. We were just unconditionally initializing the dropdown to the empty array. This PR changes it to use the list of categories that were already being passed into the component as props.

Fix CategoryDropdown initial value.

---

app/components/Edit/CategoriesDropdown.js

My last PR broke the ability to add a new service to a resource because I wasn't properly handling the case where you might pass in `null` to the CategoriesDropdown component. Now I use the `defaultProps` member of the React component to set the default value to `[]`. I manually tested that this fixes the issue for me locally.

Handle null categories on CategoriesDropdown.

---

.travis.yml
app/components/Edit/EditPhones.js
app/styles/components/_org-page.scss
package-lock.json
package.json
testcafe/config.js
testcafe/editResource.js
testcafe/home.js
testcafe/pages/EditPage.js
testcafe/pages/FindPage.js
testcafe/pages/ResourcePage.js
testcafe/pages/SearchPage.js
travis-testcafe.sh

Don't merge yet, still working out the kinks with getting it working in Travis.
In case if you want to try using these for the QA party tonight, here's my branch where I've added [TestCafe](https://devexpress.github.io/testcafe/) end-to-end tests.
It's a framework for running end-to-end tests (read: real browser tests) that injects your tests onto an existing web page. Architecturally, they spin up a lightweight proxy server that wraps your web page, and when you connect a browser to the proxy server, it serves the requested page with the test driver injected into it.
It's essentially an alternative to writing Selenium tests, and I've found it nice to use because it mimics many of the common HTML5 DOM APIs and because they've added a lot of reasonable default behavior that Selenium lacks, …

Add end to end testing

---

app/components/Search/ResourcesRow.jsx
app/components/Search/ResourcesTable.js

In the past, the `Open Now` filter on the resource list page did not account for when a resource was open past midnight on a particular day. 
For example, imagine it's Sunday at 2am and the current resource is open from 8pm-4am on Saturday. In this case, we would still want to display the resource as open even if the schedule is for the day before (Saturday). 
Now, I've added special logic to handle this case and confirmed that this is now working as intended.

Open now filter fix

---

README.md
travis-testcafe.sh

Did a little bit of cleanup by adding build status badges to the README. For Sauce Labs, I had to create a subaccount with separate credentials so that PR builds aren't mixed in with builds from master. I tested this by pushing a temporary commit that ran the master branch credentials on a normal pull request and checking that the badge shows up fine (https://github.com/ShelterTechSF/askdarcel-web/blob/a602b1ef736d8b68cd8a96bf6f8780b2eec4ad34/README.md).

Add Travis and Sauce Labs badges to README.

---

.eslintrc.js
package-lock.json
package.json
testcafe/config.js
testcafe/editResource.js
testcafe/home.js
testcafe/pages/EditPage.js

I noticed that we're not linting the TestCafe tests, since they're located in a different directory from the normal app files. This adds them to ESLint, and also includes a bunch of corrections to the style in order to pass linting. I want to get this in before we add more TestCafe tests, before we start proliferating more bad style 😛.

Add linting to TestCafe tests and fix style violations.

---

README.md
docker-compose.yml

Depends on https://github.com/ShelterTechSF/askdarcel-api/pull/272, since there needs to be a minor tweak to how networking is set up in the askdarcel-api docker-compose instance.
This adds a very simple docker-compose.yml file that is configured to allow you to run the askdarcel-web app and connect it to a Docker-based askdarcel-api instance. It's so simple that there isn't even a new Dockerfile; we just use the vanilla `node` Docker image.
The README has been updated with instructions on how to use the new Docker flow, which I've marked as the recommended setup.

Add docker-compose.yml and Docker-based setup instructions.

---

package-lock.json
package.json

- https://github.com/sass/node-sass/issues/1945 says
that our current version of node-sass is not compatible
with node v8, so I updated our version of node-sass

Issue #405: Fix error when building with Docker

---

README.md

There was a minor bug in the Docker instructions in the README, so I corrected it. I also rewrote the Docker instructions for running TestCafe to work with the new docker-compose workflow. I just tested all this locally to make sure that it works.

Fix Docker instructions.

---

app/components/Edit/EditSections.js

- Scenario 1: Saving a new resource creates two confirm boxes
Second box occurred because this.state.submitting !== true,
which it was. I set the state before sending the data to the
backend
- Scenario 2: Canceling changes or discarding changes created
two confirm boxes when there were changes. This was because
the handleCancels function showed a confirmation box while
the keepOnPage funcion showed the second. The keepOnPage
function was called called if any inputs were dirty, so it
is more robust, so I kept that one.

Issue #394: Fix bugs where there are double confirm boxes

---

docker-compose.yml

Newer versions of Docker for Mac support different caching options for macOS volume mounts. Using the `delegated` mount option allows the container and host to temporarily be out of sync, making the container's view authoritative, which can improve performance because writes within the container do not need to propagate to the host before they return.
Empirically, this slightly speed up the Webpack build from ~40s to ~35s on my MacBook Pro.
https://docs.docker.com/compose/compose-file/#caching-options-for-volume-mounts-docker-for-mac

Use delegated volume mount to increase Docker performance on macOS.

---

testcafe/editResource.js
testcafe/newResource.js
testcafe/pages/EditResourcePage.js
testcafe/pages/NewResourcePage.js

This sort of but not fully implements #427. It adds a basic test that visits the new resource page, fills out the minimum amount of information that won't trigger a server validation error, and hits the submit button.
What isn't easy for me to test is that the filled out information is actually present on the show page. This is because after you hit the submit button, it takes you to the home page, and it's not easy to find the show page for the resource you just created.
While I would prefer to ship what I have now and defer actual changes to the app to a separate PR, what you all think about changing the behavior of the submit button to redirect you to the show page of the resource that was just created? That would make testing a lot easier.

Add basic test for New Resource Page.

---

app/components/Resource/Resource.jsx
app/components/Resource/ResourceInfos.jsx
testcafe/editResource.js
testcafe/pages/EditPage.js
testcafe/pages/EditResourcePage.js
testcafe/pages/ResourcePage.js

Fixes #419 and #428, except I'm going to claim that some of the things mentioned in those tickets are better done with other TestCafe tickets.
From #419:
> --Open status (either as "Open until x" or "Closed")
Should be done with one of the tickets related to schedule days.
> --Each address associated with the resource
> --Each phone number associated with the resource
Already done previously.
From #428:
> --Address and related fields
Already done previously.
> --Phone(s) (number and service type)
This should be done with some of the other tickets related to adding/removing phone numbers.
The email on a resource wasn't easy to select because the DOM element it is in has the class "website"  for some reason. I did a bit of refactoring so that there's an Email component, similar to the …

Test editing and viewing resource fields

---

app/components/Edit/EditSections.js
app/styles/components/_edit.scss

Fixes #534.
I figured out that the reason the submit button fails to work after you encounter an error on the create new resource page is that the button gets permanently disabled, due to setting the `submitting` state to true. Once the button is disabled, it's no longer possible for it to actually create a submit event. I fixed this by resetting the `submitting` state if an error occurs.
The second issue is that it's not obvious from a UI perspective that the button is actually disabled. Not only does the button not change appearance, but the cursor is still the `pointer` cursor, which makes it look like you can actually click it. To fix this, I added a bit more CSS to both change the color of the button and set the cursor to the `not-working` icon.
@derekfidler, LMK if this styling …

Fix borked create new resource page when an error occurs

---

app/components/Search/SearchResultsContainer.jsx
app/styles/components/_search-result-table.scss

fixed a visual bug if the returned search results had a very short description resulting in the results section to take less than half the screen.
improved the padding of the "no search results" text so it doesn't look broken.

visual styling bugfix

---

app/components/Search/ServiceEntry.jsx

Currently, on the search results page, all services display "No address found". Turns out this is because we were trying to access the `.address` instead of `.addresses` property. The property itself is confusingly named because `.addresses` actually just points directly to a single Address instead of an array of addresses. Fixing this makes the page look right.

Fix service address on search results page

---

.travis.yml
config.example.yml
testcafe/listings.js
testcafe/pages/EditPage.js
testcafe/pages/ResourcePage.js
testcafe/pages/SearchPage.js
travis-testcafe.sh

This PR is basically two main changes:
1. Adding a new Google API for use in development/staging which can access the Google Maps APIs
2. Fixing the TestCafe tests that have been broken while we weren't running them, since the structure of the pages has changed.
Note: I did make one major change to our Travis CI settings (from the web UI, not .travis.yml), which was to remove the `ALGOLIA_INDEX_PREFIX`, which was previously set to `production`. I needed to make this change in order to ensure that the web and api instances that run in Travis are actually using the same Algolia index, which is now required because we got rid of some of the legacy endpoints that allowed us to bypass Algolia search.
This shouldn't be necessary anymore because the web Docker images can now read that value from …

573 Restore TestCafe tests

---

README.md

I just followed the README on my work laptop and realized that the instructions are out of order. The instructions used to have you create your `config.yml` file *after* trying to run `npm run build`, which doesn't work. I moved that stuff up higher, and I deleted the old instructions that described setting up the `.env` file, which isn't being used anymore.

Replace the old .env setup instructions with config.yml instructions

---

app/components/ui/BasicNeedsBlockConfig.js
app/components/ui/LandingPageResourceBlock.jsx
app/components/ui/LegalBlockConfig.js
app/styles/components/_landing-page-card.scss
app/styles/components/_landing-page-resource-block.scss

I noticed that the landing page wasn't displaying correctly on mobile since the widths of the "Discover X resources" sections were hardcoded and too large for mobile. I messed around with the HTML and the CSS to make it look good on both desktop and mobile.
Note that previously we had explicitly split the cards into two separate FIRST_ROW and SECOND_ROW arrays. I joined them into a single one and used flexbox to make them display in two rows on desktop and a single row that can scroll to the right on mobile, per the Figma mockups.
(Note the gray area at the top that ends halfway horizontally is the true width of the page. Everything in white is past the screen on mobile.)

Fix landing page on mobile.

---

app/components/ui/LandingPageResourceBlock.jsx

This makes the links work properly locally.

Change hardcoded URL base for landing page resources to a relative URL.

---

app/components/layout/CategoryItem.jsx

This fixes the bug where we weren't escaping the category name, and where having an & in the category name would mess up the search URL. Tested locally to make sure that clicking on a category with an ampersand in the name yields a page with actual search results.

Escape query parameter before using in URL.

---

app/components/listing/TableOfOpeningTimes.jsx

Sorted table of opening times with a utils function.
Perhaps we could sort the data itself instead of just in this view, but I didn't see a common Schedule object in which to do that.

[648] Fixed service opening / closing days appearing in random order

---

app/components/ui/Navigation.jsx

The mobile search input reference was overwriting the desktop reference.
Refactor so that each search box edits the same `query` value, which is
stored in the component's state.

Fix query submission on search results page

---

app/components/listing/Services.jsx
app/styles/components/_org-page.scss

Added a simple link around the header text. This follows the same styling as the links in services nav section that links to the header elements. Let me know if you'd like an alternate style.

[658] Added hyperlink from Service header in Resource page to Service page.

---

app/components/search/SearchTabView.jsx
app/components/search/ServiceEntry.jsx

Fixed the confusing search result item tab order from defaulting to "How to Apply" to defaulting to "Description"
Before:
After:

Switched default search results tab from How to Apply to Description

---

travis-testcafe.sh

I think the SauceLabs/Travis tests are failing because SauceLabs slightly changed their API. Previously we were telling SauceLabs to use the `beta` version of Chrome, which would allow us to always be running on a new version of Chrome. At the time the only alternative was to run on a fixed version of Chrome.
It seems that since then, you are now able to specify `latest`, `latest-1`, or `latest-2` for the latest, second to latest, or third to latest versions of Chrome, so now I've updated our TravisCI script to run on the latest version: https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options

Use fixed version of Chrome.

---

app/components/edit/EditSchedule.jsx
app/components/edit/ProvidedService.jsx
app/pages/OrganizationEditPage.scss

When editing a service, there will now be an option to have the service inherit its schedule from its parent:
When selected, the edit hours table will be hidden:
Note that resources (top level) won't have this option.

#637 - Add ability for service to inherit schedule from parent resource

---

app/components/edit/EditSchedule.jsx

If a service has an empty schedule, we automatically inherit its schedule from its parent. When the service schedule is being inherited from its parent, we hide the schedule block.
The bug here was that an organization had an empty schedule, which we then assumed meant it was inheriting its schedule and therefore hid the schedule block. The issue was that we did not take into account whether or not this resource was actually capable of inheriting its schedule, and whether or not we had a checkbox displayed to toggle it out of the hidden state.
We have a prop `canInheritFromParent` that determines whether or not the given resource is able to inherit its schedule (ie an Organization cannot inherit its schedule, but a service can). In this case we weren't taking this prop into account when …

Fix schedule in resource creation

---

.eslintignore
app/components/edit/EditServices.jsx
app/components/edit/FormTextArea.jsx
app/components/edit/ProvidedService.jsx

As I continue with refactoring the frontend app in order to fix the schedule handling code, I've been trying to hoist state up the component hierarchy. I think a pretty big problem that we have with our current code is that there is React Component state that is duplicate at several different layers, and state changes have to be propagated upwards and applied at every layer.
This PR represents one step of the refactoring, where I've hoisted state out of the `<FormTextArea>` component. In this component the state is less obvious, but because we're using a normal HTML form element, there is actually implicit state on the `<textarea>` element. React does give you the ability to let a parent component manage the state of a form element, which is what they call a [controlled …

Hoist state out of FormTextArea

---

.eslintignore
app/components/listing/ActionSidebar.jsx
app/components/listing/ActionSidebar.scss
app/components/listing/MobileActionBar.jsx
app/components/listing/MobileActionBar.scss
app/pages/OrganizationListingPage.jsx
app/pages/ServiceListingPage.jsx
app/styles/components/_admin.scss
app/styles/components/_listing-page.scss
app/styles/components/_org-page.scss
app/styles/st-base/_layout.scss
app/utils/ResourceActions.js
testcafe/pages/ResourcePage.js
testcafe/pages/ServicePage.js
webpack.config.js

The new designs for the Organization Listing Page and the Service Listing Page are very similar. So, in implementing the Organization Listing Page redesign, I'm attempting to pull out as many shared components as possible. I started with the actions bars (we have one that we display on desktop, and another that we display on mobile).
Designs can be found on figma, here: https://www.figma.com/file/H0kD6ZZPhPR2RMyNJHWWeTtI/Web-Client?node-id=1456%3A1223
These components were partially implemented in the Service Listing Page, already. In this PR I further componentized them by moving more logic into the components and cleaning up the css. Once they were more self-contained, I was able to replace the actions bar on the Organization Listing Page with these components.

Componentize resource listing actions bar

---

app/components/listing/Services.jsx
app/components/search/SearchTabView.jsx
app/pages/ServiceListingPage.jsx

The issue here was that there were several places where we were referring to markdown content without wrapping them in the appropriate component. Although issue 570 references issues with the organization description on the main org page, I found no issues with the markdown parser there. However, the services section of the main org page, the search page, and the services page all had the issues as described.

[570] Fixed references to markdown content without markdown styling

---

webpack.config.js

When I put together [this PR](https://github.com/ShelterTechSF/askdarcel-web/pull/721), the styles for `ActionSidebar` and `MobileActionBar` were working as expected. However, this PR got merged and now when I start up master, the styles are not being applied properly. I understand the issue (they are being built as css modules but being used as regular stylesheets), but I don't understand why they were working locally for me before.
I don't have time to update these components to use css modules right now, but I don't want to leave master in a broken state. So, I've just updated our webpack loaders so these particular files are not built as css modules.
Before:
After:

fix broken styles

---

app/components/edit/FormTextArea.jsx
app/components/edit/ProvidedService.jsx

This PR does some refactoring to the `ProvidedService` component on the edit page. I think the main things I succeeded at improving are:
1. Changing various simple text input fields from stateful components to controlled form components, thereby hoisting the state into the `ProvidedService` component,
2. Collapsing the `handleFooChange()` methods into a single method, and
3. Adding a `flattenedService` variable to the `render()` method that collapses both the version of the service passed in as a prop with the version of the service which is part of the state. For some reason, much of our code only stores the changes to objects in the state, but not the whole object, so it makes it trickier to control children components when the prop and the state have separate, incomplete info. With …

Refactor ProvidedService

---

app/components/edit/EditServices.jsx
app/components/edit/ProvidedService.jsx
app/pages/OrganizationEditPage.jsx

My next step for refactoring the frontend code is moving state out of the `EditServices` component, moving some functionality up into the `OrganizationEditPage`. This was an example of us duplicating state between multiple layers of the app, causing us to have to synchronize changes with each layer of the app.
Now `EditServices` is a stateless component, and all handler methods are passed in from above. Note that some of `EditServices`' descendant components may still have state in them.
One last note is that state about services is stored in two different places in `OrganizationEditPage`. My PR didn't change any of that; this was already the case. Services state is either stored in `this.state.resource.services` or in `this.state.services`. The difference between the two is that the …

Remove state from EditServices

---

app/components/search/ResourceEntry.jsx
app/components/search/ServiceEntry.jsx

Uses the same Google Maps URL that is generated on the Actions side bar,
which only requires the destination lat-lng pair.

Fix Directions link on Search Results (#341)

---

app/pages/OrganizationEditPage.jsx

I think the bug with creating schedules for new services was introduced by my hoisting of state up the component hierarchy. Now new services may have `null`s in some of their schedule days, and if they aren't touched in the new service form, it ends up sending invalid data to the backend. This adds a quick guard to filter out any ScheduleDays that have null `opens_at` or `closes_at` attributes.

Fix creation of schedules for new services.

---

app/components/edit/EditServices.jsx
app/components/edit/ProvidedService.jsx
app/pages/OrganizationEditPage.jsx

I think this is the last Component that I need to move state out of before I can finally work on EditSchedule. With this change, there are no layers of state between the OrganizationEditPage and the EditSchedule, so then I can more easily hoist state out of EditSchedule, and then afterwards finally fix the multiple implementations of timezone handling.
This PR is much less scary to look at if you look at the diff with whitespace changes ignored.

Hoist state out of ProvidedService.

---

app/components/edit/EditSchedule.jsx
app/components/edit/EditScheduleDay.jsx
app/components/edit/ProvidedService.jsx
app/pages/OrganizationEditPage.jsx
app/utils/index.js

This is hopefully the final of all the refactoring PRs that I'm doing before I can finally work on https://github.com/ShelterTechSF/askdarcel-web/issues/647.
With this PR, all of the React state related to schedules on the Edit page will be moved up to the top level, which ensures a single canonical representation of schedule-based state on the page. This, I believe, is a vast improvement over the old version of code, where the schedule state was represented at four different levels, and they all had to be kept in sync with each other, which made changing the representation of the schedule very difficult.
Just to recap, here's what the Component hierarchy on the Edit page looks like:
- OrganizationEditPage
- EditSchedule (for the resource)
- EditServices (wraps the collection of all …

Hoist edit schedule state up to the top

---

app/components/edit/EditAddress.jsx
app/components/listing/ResourceInfos.jsx
testcafe/editResource.js
testcafe/pages/EditPage.js

Allow users to include a "Name" field when editing an address. This is
useful for resources/services with multiple locations.
See also: https://github.com/ShelterTechSF/askdarcel-api/pull/421

Add "Name" field to addresses (#305)

---

app/pages/OrganizationListingPage.jsx
app/styles/components/_listing-page.scss
app/styles/components/_org-page.scss

Moved the mobile actions bar (`Call`, `Directions`, `Edit`) up to the correct place. Cleaned up padding between sections.
BEFORE
AFTER

General styling clean up of resource page

---

.eslintignore
app/components/search/SearchTabView.jsx

This is a little bit of refactoring I'm doing to make it easier to unify the representation of times, since there are some unused codepaths in the `SearchTabView` that the linter will flag.

Fix lint for SearchTabView component.

---

app/actions/serviceActions.js
app/components/listing/TableOfOpeningTimes.jsx
app/pages/OrganizationListingPage.jsx
app/pages/ServiceListingPage.jsx
app/utils/DataService.js
app/utils/RecurringSchedule/constants.js
app/utils/RecurringSchedule/index.js
app/utils/RecurringSchedule/models.js
app/utils/transformSchedule.js

This is the beginning of actually attempting to fix up the open/close times across the site. What I've done here is define a few data structures that are meant to centralize the logic for handling open/close times and begin to migrate the codebase to use them. The data structures all live in `app/utils/RecurringSchedule/models.js` and are named:
- `RecurringTime`, which represents the 3-tuple of (day of week, hour, minute)
- `RecurringInterval`, which represents the 2-tuple of (open time, close time)
- `RecurringSchedule`, which represents an array of `RecurringInterval`s.
I've added a couple new functions to the `app/utils/DataService.js` module — `getResource()` and `getService()` — which makes API requests and, before returning them to the caller, parses the results into the above data …

Begin cleaning up open/close times 

---

app/components/layout/OrganizationCard.jsx
app/pages/OrganizationListingPage.jsx
app/pages/ServiceListingPage.jsx

Remove HAP verified badge.
Note that this component was also in the service listing page, but it doesn't look like it was ever actually rendering since the verification lives at the resource level. Went ahead and removed the component anyway.

824 - Remove HAP badge from resource page

---

app/components/listing/DetailedHours.jsx
app/components/listing/RelativeOpeningTime.jsx

The org resource pages were showing things like "Open Now" when they had schedules marked with unknown hours.
This resolves this and the services inside the resource page still listing their schedules (even if they had "hours unknown" schedules.)

[442] Fixed the listing page incorrectly displaying hours when hours are unknown

---

app/components/listing/RelativeOpeningTime.jsx

This should fix some issues with bad listing data on the search page - although for these resources / services, they will show as "Closed Today."

Added a null/undefined check for schedules with nil intervals.

---

webpack.config.js

Although this makes it such that the youth guide pdf appears at the unattractive URL `/dist/youthguide.pdf`, we suspect that this is a change that may have broken staging and should investigate alternative means of rerouting the pdf link.

Revert changes to webpack.config.js from Casey youth guide pdf.

---

.travis.yml

Ever wonder why we get two Travis CI build statuses for each PR? It's because Travis CI has [two types of builds](https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests), branch builds and PR builds. The main difference is that the PR build will merge in the target branch before running the build, which can catch cases where conflicting changes have been merged into the target branch.
This PR will change the Travis CI settings so that we don't do branch builds on PRs, and so that branch builds only happen on `master` and any branch or tag matching the format consisting of numeric digits separated by periods. The latter is important, since it affects our deploy process, so if I screwed this up or if we change our tagging format, we'll need to update the Travis CI …

Only do Travis CI branch builds on master and release tags.

---

app/components/App.jsx
app/pages/OrganizationListingPage.jsx
testcafe/pages/ResourcePage.js

The reason I'm making this change is actually because I'm trying to upgrade a bunch of dependencies including react-router, but the `React.Children.map()` in the middle of the main `App` component is causing me some trouble, since react-router completely changed between v3 and v4 and we can't easily map over the children pages like this anymore.
What this PR does is get rid of the `React.Children.map()`, which was only being used to automatically pass the `userLocation` prop to all the children of the `App` component, which we can instead do with Redux. In fact, someone had already added the user location to the root Redux store and passed it to the SearchPage, so the only Page component I had to change to use Redux was the OrganizationListingPage.
What this also does is completely remove …

Unify source of user location state in App component

---

app/components/search/Filtering.jsx
app/components/search/OpenNowRefinementList.jsx
app/components/search/SearchMap.scss
app/pages/SearchPage.jsx

I'm trying to untangle a bit of the logic and state on the Search results page to make it easier to upgrade to the latest react-router.
One improvement is to replace our custom logic for the Open Now button with a Algolia React InstantSearch custom RefinementList. We previously had some custom logic that had to keep track of browser history and URL and conditionally insert or remove the query parameter for "open now".
By replacing this with a custom RefinementList, we don't need to keep track of the URL state ourselves, and instead we can delegate that to the Algolia React library. This allows us to sever the dependency on `react-router` in the `Filtering` component.
In addition, it means we don't need to instantiate the `<RefinementList>` objects within the `<SearchPage>` component that …

Replace Open Now button with custom Algolia RefinementList

---

app/utils/transformSchedule.js

Fixes #374.
I made a typo a long time ago by typing `hours` instead of `hour`. Apparently the rest of the code would still run, since the typo only affected the part where it needed to shift the day by one if the closes_at time is before the opens_at time, which we normally use to represent time ranges that span midnight and close the next day.

Fix typo in datetime parsing code, affecting schedules that span midnight

---

app/components/layout/ListingTitleLink.jsx
app/components/layout/OrganizationCard.jsx
app/components/search/ResourceEntry.jsx
app/components/search/ServiceEntry.jsx
app/pages/OrganizationEditPage.jsx
app/pages/OrganizationListingPage.jsx
app/pages/admin/ChangeRequests.jsx
app/routes.jsx
testcafe/pages/ResourcePage.js

I've been working on trying to upgrade from React Router 3 to React Route 4, and one of the more annoying things to do is dealing with the query param on the Resource (Organization) listing page, since they dropped the built-in query parameter parser, and you have to parse the query string yourself.
I figured we should try to make our routes consistent anyway, so in this PR I changed the `/resource?id=` URL to `/organizations/:id`. This makes it match the services routes, which already look like `/services/:id`. I also took this as an opportunity to rename the route from `resource` to `organization`, since I believe that's the direction we want to move towards, and it's probably best to get that URL renamed before the big launch.
Lastly, I did add a redirect in place so that if you try …

Change /resource?id= URL to /organizations/:id

---

app/components/search/SearchMap.jsx
app/components/search/SearchMap.scss
app/components/search/SearchResultsContainer.jsx

When users perform a search, they are shown a list of results along with a map with markers for each of the results. Users can drag and zoom the entire map, but individual markers are not interactive. This PR displays a popover with information about the resource when a marker is clicked. Clicking through the popover takes the user to the resource detail page.
While I was in there, I also fixed a bug where the numbers on the markers do not match the numbers in the results list when the user is not on the first page of results.

#700 - Make map markers interactive

---

.travis.yml

It looks like all of our Travis CI builds are suddenly failing with the following error:
```
sh: 0: Can't open /etc/init.d/xvfb
The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .
```
[Xvfb](https://en.wikipedia.org/wiki/Xvfb) is the X virtual framebuffer, which is a way of running graphical programs on a Linux machine without rendering to an actual screen. This is a common way of running automated scripts for graphical programs on headless machines, such as Chrome on a headless Travis CI box.
I don't think we're using this anymore, since we use Sauce Labs instead for our browser testing, and therefore this stuff can be removed.
My guess for why this suddenly started failing is that Travis CI must have removed Xvfb from its default image. We could make this work …

Remove failing Xvfb steps

---

app/components/search/ResourceEntry.jsx
app/components/search/SearchEntry.scss
app/components/search/SearchMap.scss
app/components/search/ServiceEntry.jsx

This is a bit of a continuation of https://github.com/ShelterTechSF/askdarcel-web/pull/875, where I added tooltips with some details when you click on a map marker. I just noticed that these tooltips needed a little styling love for when they are displaying the `MOHCD Funded` badge.
Notice that with the current styling, the header overlaps with the MOHCD badge.
Moved the header & badge into the same flexbox so they play a little nicer with each other.
Also noticed that for some reason we were showing the badge regardless of whether or not a resource actually had the `is_mohcd_funded` property as true on the backend. Fixed that while I was in there.

Fix styling of MOHCD Funded badge on map tooltips

---

app/components/listing/ActionSidebar.jsx
app/components/search/SearchResultsContainer.jsx
testcafe/editResource.js
testcafe/pages/EditResourcePage.js
testcafe/pages/ResourcePage.js
testcafe/pages/ServicePage.js
testcafe/service.js

Removes the `Edit` button from the organization listing page so it can't be edited by external users. BTW - The reason I have so many commits attempting to fix tests is my local TestCafe setup isn't working for some reason and I'm trying to get this out as quickly as possible :/ Will make sure to squash commits before merging! 
**Before:**
**After:**

Remove Edit button from individual organization listing page and add org button

---

testcafe/pages/ServicePage.js
testcafe/service.js

See https://github.com/ShelterTechSF/askdarcel-web/pull/895/files#r347166009, but it looks like the reason that the TestCafe test was failing for us is because we accidentally navigated to the wrong page.
I also added in some changes to refactor the `t.hover()` into a method with a name that more obviously describes what it is doing, which is to wait for the page to load.

TestCafe: Fix Add Service Schedule Day test.

---

app/index.html
webpack.config.js

As discussed on Slack, my previous PR (#900) doesn't work for most social media sites because the meta tags created in React are only available once the React application is bootstrapped and running. We need the meta tags to be available from just loading the HTML.
Although the longer-term solution probably involves setting up server-side rendering, for now we can statically add the relevant meta tags to the base HTML template.
I checked that this works locally by downloading the HTML with `curl` without executing the React code and checking that the tags are all there. Note that you will need to run `docker-compose run --rm web npm run build` to regenerate the HTML file first if you want to test this out locally.

Add meta tags to html-webpack-plugin so that they are available statically.

---

app/index.html

Apparently links to images in the `og:image` tag need to be absolute, not relative. (https://stackoverflow.com/questions/9858577/open-graph-can-resolve-relative-url).
This is not great, but the best we can do is hardcode `https://sfserviceguide.org` as a prefix to the URL. The challenge for us is that we deploy the same Docker image in both staging and production environments, and the URL is not known at image building time since it changes depending on where we deploy to. To add to the challenge, we even have the same deployment used for both the SF Service Guide and the Ask Darcel sites, which can only tell the difference based on which URL was used to make the request.
This really will not be possible to do "correctly" without an actual "backend" to the frontend application.

Hardcode sfserviceguide.org for absolute URL to og:image.

---

package-lock.json
package.json

I wanted to keep up to date with the latest versions of libraries, so this PR bumps various TestCafe-related dependencies.
testcafe itself was only bumped up to 1.6.0, not 1.7.0, since the latter was not running properly on my laptop. I'm not sure why there was an issue, but I figured it's worth bumping to at least the latest version of testcafe that runs on my laptop.

Bump TestCafe dependencies.

---

package-lock.json
package.json

The latest version of [nyc](https://github.com/istanbuljs/nyc) apparently does not depend on handlebars anymore, so this will also make https://github.com/ShelterTechSF/askdarcel-web/pull/903 unnecessary.

Bump nyc to the latest.

---

app/components/edit/EditAddress.jsx
app/components/edit/EditSchedule.jsx
app/pages/OrganizationEditPage.jsx
app/pages/OrganizationEditPage.scss

See @Maxastuart 's report in channel for context: https://sheltertech.slack.com/archives/C0EGCTDCL/p1580195509055400
There were a few issues here. 
1) The first was that the API was throwing a 500 on submission because we were trying to send a resource with an `addresses` field and it only knows how to handle POSTs with an `address` field. 
2) Next, we weren't rendering an hours template for the new resource because we were generating the temporary schedule object and adding it to the component state nested in the `resource` object. It should be directly on component state.
3) Finally, the API errors if you send a schedule day with a null `opens_at` or `closes_at`. So, had to add some additional cleaning of the schedule before actually sending it up to remove any schedule days that had …

Fix New Org Creation

---

app/components/search/SearchEntry.jsx
app/components/search/SearchMap.jsx

Today I learned that the object destructuring syntax in JavaScript treats `null`s differently than undefined keys. Basically, `const { foo = [] } = {}` will set `foo` to `[]`, but `const { foo = [] } = { foo: null }` will set `foo` to `null`.
This seems to only affect the code related to the Algolia search results, since they seem to always return `addresses: null` rather than omitting the key, which meant that us trying to set a default value of the empty array wouldn't work properly. This separates out those assignments into two separate lines to force it to handle the case where the key is explicitly present but set to `null`.
I tested this locally by configuring by local setup to point to the staging server's Algolia index, which seemed sufficient for reproducing the bug.

Explicitly handle case where addresses is null, not undefined.

---

.eslintrc.js
app/components/edit/EditCollection.jsx
app/components/edit/EditNotes.jsx
tools/cli/approveChangeRequests.js

The [`no-plusplus`](https://eslint.org/docs/rules/no-plusplus) rule disallows the use of the `i++` unary operator, and it is enabled by default in the Airbnb style guide. This PR deletes the line in our `.eslintrc.js` so that it is enforced again.
I'm of the opinion that we should 1) stick as closely as possible to common style guides and 2) that most usages of `i++` are in loops where we should prefer `.map()`, `.flatMap()`, or `.reduce()` anyway, so I'd prefer to re-enable the rule.
It's also simple enough to type in the allowed `i += 1`, which is not vulnerable to the potentially awkward semicolon insertion issue that the rule was designed for.

Re-enable no-plusplus ESLint rule.

---

app/components/edit/EditAddress.jsx
app/pages/OrganizationEditPage.jsx

As mentioned in https://github.com/ShelterTechSF/askdarcel-web/pull/889#issuecomment-570960935, this is my attempt at refactoring the state management on the Edit page with respect to addresses to simplify the supporting of multiple addresses.
This is branched from https://github.com/ShelterTechSF/askdarcel-web/pull/894, so the diff will be messy and include the stuff from that PR until that PR merges in to master. In the meantime, you can look at the following diff view to see what was added in this PR: https://github.com/ShelterTechSF/askdarcel-web/compare/akalkanis_885_resource_page_multiple_addresses...refactor-edit-address-state
Basically what I tried to do was remove all React state from the `<EditAddress>` component, and hoist whatever necessary state into the OrganizationEditPage …

Refactor EditAddress state

---

app/components/App.jsx
app/components/ui/Banner/Banner.jsx
app/components/ui/Banner/Banner.scss
webpack.config.js

Temp banner on homepage:
Banner will show up on all pages:

add temporary covid banner

---

app/components/ui/Banner/Banner.jsx
app/components/ui/Banner/Banner.scss

See conversation here: https://sheltertech.slack.com/archives/C010E72NA0Z/p1585426146299600
Laura asked that we update the banner copy so that it does not say that this resource guide is ours.

Update banner copy

---

app/components/ui/Banner/Banner.jsx
app/components/ui/PopUpMessage.scss

Just reverting the banner copy to make clear that the covid list is ours. 
Also noticed that we have the success pop up always rendered on the screen with an opacity of 0 and it sometimes obscures things underneath it (ie the `Resource Guide` link in the banner). The opacity is nice as-is so that it has a transition, so I just dropped the z-index to a negative number when its hidden and then it gets pulled up to the front when shown.

revert banner copy and push hidden pop up to bottom of stack when hidden

---

app/reducers/index.js

My [bugfix to eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/pull/1640) finally made it in the latest release, so I want to make use of it and detect a bunch of unused imports.
The first set of things I found I wasn't even really expecting, which is that we have some completely empty JavaScript files lying around. This PR deletes them (and fixes some code that was somehow importing one of them).

Remove empty modules.

---

config.example.yml

A number of people have accidentally thought that you need to leave in the `<` and `>` symbols in the ALGOLIA_INDEX_PREFIX in `config.yml`. I added a comment just above it that hopefully makes it very clear that you should replace the `<` and `>` symbols as well.

Clarify the ALGOLIA_INDEX_PREFIX instructions in config.example.yml.

---

app/components/ui/Modal/Modal.jsx
app/components/ui/Modal/Modal.scss
app/components/ui/Modal/ServiceDiscoveryModal.jsx
app/components/ui/Modal/ServiceDiscoveryModal.scss
app/pages/HomePage/components/GuideList/GuideList.jsx

This PR hooks the new service discovery flow up to the new food category (id `1000001`). In addition, I realized I never added the footer & buttons to the eligibilities view. So, this adds them. Here's what it looks like with some dummy-data:
We probably want to think about what we want to do about the intercom thing in this view. But for now I just pushed the buttons over a little bit so they aren't obscured by it.

Hook eligibility modal up to food category

---

app/pages/ServiceListingPage.jsx

This has since been replaced with the `eligibilities` field, which is an enumerated type, and there's no longer a way to edit the old `eligibility` field.

Remove legacy eligibility field from ServiceListingPage.

---

app/pages/ServiceDiscoveryResults/RefinementListFilter.jsx
app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.jsx

I was trying to debug some of the issues that we were seeing in prod when I noticed that there was a lot of stuff that we were doing in RefinementListFilter that's unnecessary, since the Algolia helpers already do a lot of that work. I redid the component to look more like [the example in the Algolia docs](https://www.algolia.com/doc/api-reference/widgets/refinement-list/react/#create-and-instantiate-your-connected-widget), where we don't define any custom props, since Algolia already has them.
I think this simplifies the component because there's no longer any state, as all the state is derived from the Algolia higher-order component helper that ties it to the context created by the containing `<InstantSearch>` component.
One of the more notable difference is that now the …

Refactor RefinementListFilter to reuse existing Algolia functionality.

---

app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.jsx

Fixes a bug I introduced in https://github.com/ShelterTechSF/askdarcel-web/pull/958.
I had a minor typo, where `array.include()` should have been `array.includes()`. I hadn't tested it previously, since I wasn't able to get local data working, but I managed to fake some data in my local setup to test the categories flow.

Fix minor typo in subcategories filter.

---

app/components/ui/Modal/ServiceDiscoveryModal/ServiceDiscoveryModal.jsx
app/components/ui/Modal/ServiceDiscoveryModal/constants.js
app/pages/HomePage/components/GuideList/GuideList.jsx
app/pages/ServiceDiscoveryForm/ServiceDiscoveryForm.jsx
app/pages/ServiceDiscoveryForm/index.js
app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.jsx
app/pages/ServiceDiscoveryResults/index.js
app/routes.jsx

This included some refactoring to make the ServiceDiscoveryResults component its own standalone react-router route.
Here's what it looks like (note the address bar of my browser):
I could definitely use some more guidance on what the URLs should be (@JacobDFrank?). For now, it's just at `/service-discovery-results/:category_id`, but it causes it to have a kind of goofy URL because we started the category ID at 1,000,001.
I learned how to properly sync the Algolia InstantSearch state with the browser URL and react-router, which is covered in [a specific document in the Algolia docs](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/). Their example made use of React Hooks, so I also went ahead and changed the class-based component to a function-based …

Give service discovery forms and results their own pages.

---

app/pages/ServiceDiscoveryResults/SearchResults/SearchResults.jsx

@jjfreund noticed that the ServiceDiscoveryResult page blows up if a result doesn't have a phone number. This PR adds some logic to check if a phone number exists before trying to use it.
I also pulled the inner loop into its own component so that it'd be easier to add code to compute the conditional check. The diff is smaller if you ignore whitespace changes.

Handle case where ServiceDiscoveryResult doesn't have phone number.

---

app/pages/ServiceDiscoveryResults/SearchResults/SearchResults.jsx

This fixes a few issues with actions you can take on a search result
1. [We weren't showing `Get directions` for services](https://app.clubhouse.io/sheltertech/story/1528/add-get-directions-button-to-service-results-page)
2. [Clicking `Get Directions` was broken](https://app.clubhouse.io/sheltertech/story/1546/get-directions-links-all-lead-to-object-advjective)
3. [Clicking on `Call: ####` was broken](https://app.clubhouse.io/sheltertech/story/1549/remove-hyperlink-from-all-phone-numbers-on-search-results-page)
4. [We want to remove the `Report Error` link](https://app.clubhouse.io/sheltertech/story/1551/remove-report-error-link-from-search-results-page)

Fix sidebar links

---

app/pages/ServiceDiscoveryResults/RefinementListFilter.jsx

This allows the element to naturally flow on the page instead of unnecessarily capping it at 200px.
The `refinement-ul` CSS style originally came from the search results page, where we have a multi-column layout, so it's not actually appropriate to reuse it on the Service Discovery results page.
Note that you should review the diff with whitespace changes ignored, since I removed an unnecessary `<div>` element as well.

Remove unnecessary styling for RefinementListFilter.

---

app/pages/ServiceDiscoveryResults/SearchResults/SearchResults.jsx

Render descriptions as markdown

---

app/pages/ServiceDiscoveryForm/constants.js

It's actually kind of neat how easy this change was to make. By removing any other STEP from the list, it'll just automatically redirect you to the search results page.

Skip questionnaire and go directly to results page for internet resources.

---

app/pages/ServiceDiscoveryForm/ServiceDiscoveryForm.jsx
app/pages/ServiceDiscoveryForm/ServiceDiscoveryForm.scss

This updates the footer of the service discovery form to match the mockups in https://www.figma.com/file/lhmZSzRw4mbDpil3CZ7tsC/SFSG-Topic-listings---For-production?node-id=0%3A1
I updated the buttons to match the guide, and I also added a progress bar. However, I hid the progress bar when there's only one page of questions (which I think is all of them), since it's kind of silly to see a full progress bar with 1/1 pages on every page. However, I can change this if @JacobDFrank wants the progress bar to always be there.
Here's what it looks like, including with some faked out data to make the progress bar show up:
---
Also, this is the first time I ever learned about the HTML [`<progress>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) element, which is kinda neat. I …

Update buttons and add progress bar.

---

app/pages/HomePage/HomePage.jsx

This PR covers a few little typos/clean up of the homepage. Namely, the following 3 tickets:
- https://app.clubhouse.io/sheltertech/story/1633/fix-typo-in-homepage
- https://app.clubhouse.io/sheltertech/story/1673/correct-explanatory-text-on-homepage
- https://app.clubhouse.io/sheltertech/story/1674/correct-text-on-pathway-links-and-remove-access-points-pathway

Various home page clean up

---

app/pages/ServiceDiscoveryResults/SearchResults/SearchResults.jsx

Move org name up to under title in service discovery search results
https://app.clubhouse.io/sheltertech/story/1719/move-organization-name-directly-under-service-name-on-new-search-results-page

1719 - move org name under title in results

---

app/pages/ServiceDiscoveryResults/SearchResults/SearchResults.scss

remove scroll in sideLinkText to get rid of the gray boxes
https://app.clubhouse.io/sheltertech/story/1722/on-some-environments-images-in-search-results-page-appear-with-gray-background
before:
after:

1722 - remove scroll to get rid of gray box in results

---

package-lock.json
package.json
testcafe/home.js
testcafe/pages/FindPage.js
travis-testcafe.sh

This is an attempt to try to make TestCafe and SauceLabs less flaky by upgrading some of the libraries. I also bumped up the version of the Chrome browser we are testing to the latest release (87).

Upgrade testcafe

---

app/components/listing/TableOfContactInfo.jsx

The problem here is that: The service listing page did not update the service website when the service had a website inputted. It always kept the resource's website.
The Service page (within resource listing), however, did update the service website.
The error was found in service listing. Within ServiceListingPage.jsx, we have the "Table of Contacts info" which contains the service website. TableofContactInfo.jsx is a component, and there error is that:
The class ContactInfoTable has the constant website. This variable has the logic "service.website OR resource.website". I switched item.website to item.url, because service website is called url insteal of website in the API.

Re-do: Service Listing page not updating service website

---

app/components/App.jsx
app/components/listing/ActionSidebar.jsx
app/components/listing/MobileActionBar.jsx
app/components/maps/MapOfLocations.jsx
app/components/ui/Navigation/Navigation.jsx
app/components/ui/Navigation/Navigation.module.scss
app/styles/utils/_colors.scss

Responding to whitelabel feedback from SFFamilies.
Affects SFFamilies whitelabel **only**:
- Removed COVID banner, Intercom, search bar, and rightside nav not desired by SFFamilies (only for SFFamilies whitelabel)
- Increased the size of the SFFamilies nav logo and changed the nav bar background color to match sffamilies.org more closely
Affects **both** SFSG and SFFamilies:
- Removed the unused "Mark Correct" button in the resource action sidebar
- Removed the "Edit" button from the mobile actions, as we wanted to stop exposing this action in the first place
- Fixed an issue where the service page would not load if the MapOfLocations component failed to reach google apis

Added more / conditional styling for SFFamilies 

---

app/components/ui/Navigation/Navigation.jsx

I was poking around on the staging site, and then at some point I realized that I was on the production site for some reason. I figured out it was because I had clicked on the SF Service Guide logo in the nav bar, which always links to the production site even when you're on staging.
This is confusing, and it's possibly the reason why @fredciaramaglia noticed that there was some dummy data that a ShelterTech user had entered into the production site, since it's not obvious at all that you've switched sites from clicking on the logo in the nav bar.
This link was intentionally changed recently in https://github.com/ShelterTechSF/askdarcel-web/pull/1015 to do this, but we really only want this behavior on the SF Families whitelabel site. For all other environments so far, it's safer to just …

Have Navigation logo go to root URL when not on SF Families whitelabel.

---

app/components/ui/Navigation/Navigation.jsx

This removes the top level navigation buttons from SFFamilies. Free text is not yet supported, and all the hamburger menu items are SFSG related.
Note that the original SFSG / askdarcel sites retain their elements:

Remove mobile navigation buttons from SFFamilies whitelabel

---

app/components/edit/EditAddress.jsx
app/components/edit/EditCollection.jsx
app/components/edit/EditPhones.jsx
app/pages/OrganizationEditPage.jsx

Having trouble getting the previously saved address to populate after I add the `Add` button from the `editCollectionHOC` component. Trying to re-use what we already have similar to how we're doing it for the `EditPhones` component [here](https://github.com/ShelterTechSF/askdarcel-web/blob/master/app/components/edit/EditPhones.jsx) but it's not working properly. I'm probably doing something silly because my React knowledge is pretty rusty. 
I also tried starting again from master and just adding the `editCollectionHOC` component but I'm running into the same issue.

Add multiple addresses edit page

---

app/components/ui/Banner/Banner.jsx

This updates the COVID banner on our site with the latest vaccination information in San Francisco.

Update COVID banner with latest vaccine information.

---

app/components/edit/EditSidebar.module.scss
app/components/search/SearchEntry.scss
app/components/search/SearchMap.scss
app/components/search/SearchResultsContainer.scss
app/components/ui/Navigation/Navigation.module.scss
app/components/ui/PopUpMessage.scss
app/pages/OrganizationEditPage.scss
app/styles/utils/_layoututils.scss

In order to prevent an arms race of larger z-indexes, this change
removed z-indexes from elements that do not need them and reduces
the z-index values of elements that do need them. It also adds some
z-index: 0 values (with comments!) in order to explicitly construct a
stacking context to prevent descendant elements from hovering over
higher level sibling elements.
The remaining z-indexes are between 0 and 3.
I manually tested this on the search results page and the edit page, which were the two main pages that had z-indexes set on their elements. I also made sure to test the site in a mobile view, since some of the z-indexes are specifically for the mobile layouts.

Simplify z-index handling.

---

README.md
docker-compose.yml

I'd like to propose a change to how our Docker development environment is set up in order to make it much, much faster to install NPM modules (I measured an **8x** improvement), especially from a clean slate. The downside to this proposal is that it makes the development environment more opaque, since it relies on more advanced Docker features.
Instead of bind mounting the `node_modules/` directory from the host OS (e.g. macOS), we now create a [Docker (named) volume](https://docs.docker.com/storage/volumes/) to store the `node_modules/` directory. Docker volumes are persistent file system volumes that, in Docker for Mac, live entirely within the Linux virtual machine that runs Docker, and they continue to persist even when containers are stopped.
From the perspective of a developer, the …

Use Docker named volume for node_modules in development

---

app/pages/OrganizationEditPage.jsx

This is probably going to depend on @katerina-kossler's backend PR in https://github.com/ShelterTechSF/askdarcel-api/pull/576.
@katerina-kossler and I talked about this, and we decided that changing these to real strings and not stringified integers would be less confusing and easier to implement the code for on the backend, so this changes the frontend code to send real strings. I tested this against her current PR, which accepts either strings or integers, but we decided that we're just going to remove the handling of integers to make that code cleaner.
This was only ever being used for the recent multiple addresses feature, so none of the other models should be affected by this.

Change edit address API calls to use strings, not stringified integers

---

app/pages/ServiceDiscoveryResults/SearchResults/SearchResults.jsx

@jjfreund let me know that the ServiceDiscoveryResults pages break if an organization is missing any addresses, which might be related to the multiple addresses project regarding how orgs with no addresses are represented. Previously there would be a dummy, blank address on an org, but now it's probably just returning null.
This adds an extra check to the search results page so that we handle the case where Algolia returns null or undefined for the addresses property.
Tested this locally by creating an org with no addresses, which initially broke the guided pathways results page before this one-line change.

Check for null addresses on ServiceDiscoveryResults page.

---

.eslintrc.js
app/components/edit/EditAddress.jsx
app/components/edit/EditServices.jsx
app/components/edit/ProvidedService.jsx
app/components/edit/ProvidedService.module.scss
app/pages/OrganizationEditPage.jsx
app/pages/ServiceListingPage.jsx
app/utils/DataService.js

Implements https://app.clubhouse.io/sheltertech/story/1873/ui-ability-to-associate-remove-multiple-addresses-from-services.
https://www.figma.com/file/tBRClGsxYN9m6ZvL2STB6t/WIP-Edit-Redesign---Unscheduled?node-id=2835%3A7067
Note that this depends on https://github.com/ShelterTechSF/askdarcel-api/pull/587.
Let me first start by apologizing for the quality of my code here. This is not code that I am proud of, and if someone had presented it to me, I probably would have found it to be one of the most unreadable, arcane, and dense patches I have ever seen.
This code is not pretty. It represents a lot trial and error with trying to handle all the possible cases that can occur on the Edit page. We have a combinatorial explosion of possibilities, where data must be assembled from multiple …

Allow adding/removing addresses for services

---

app/pages/OrganizationEditPage.jsx

We were receiving reports that sometimes addresses on the services get dropped when making unrelated edits to the service. This is actually a bit subtle to even notice, since our default behavior when Services don't have explicit addresses is to inherit the parent Resource's (Organization's) addresses.
I narrowed it down to this part of the `postServices()` method, which handles updates to a Service's addresses by diffing between the original Service's addresses and what has been modified by the user. The diffing logic itself was faulty, since when a service started out with having addresses but a user does not modify the service's addresses, the `addressHandles` property on the service ends up being `undefined`. The diffing logic treated `undefined` as being the same as "empty …

Check if addressHandles is undefined before continuing to add/remove addresses on Services.

---

app/utils/whitelabel.ts

Added one fix, the env configed domain is just the subdomain key, "sffamilies" etc for sffamilies.sfserviceguide.org
Also support same mapping for sffamilies-staging.sfserviceguide.org etc.

Map white label subdomains to a staging name

---

.eslintrc.js
app/components/listing/feedback/FeedbackModal.jsx
package-lock.json
package.json

We're getting silent errors with ESLint right now, due to our babel-eslint being too old to parse TypeScript files, which is an issue when we have plain JavaScript files import TypeScript files. An example of the silent errors can be seen in this [passing CI run](https://github.com/ShelterTechSF/askdarcel-web/runs/3553457316), under the "Run npm run lint" section:
```
Run npm run lint
> ShelterTech@1.0.0 lint /home/runner/work/askdarcel-web/askdarcel-web
> eslint --ext=.js,.jsx,.ts,.tsx .
Error while parsing /home/runner/work/askdarcel-web/askdarcel-web/app/utils/whitelabel.ts
Line 65, column 2: Line 65: Missing semicolon.
63 |   title: 'SF Families',
64 |   userWay: true,
> 65 | } as const;
|  ^
66 |
67 | const SFServiceGuide: WhiteLabelSite = {
68 |   appImages: {
`parseForESLint` from …
```

Fix silent ESLint errors by upgrading babel-eslint

---

.github/workflows/publish-release.yml

Some of our dependencies are too old and don't have precompiled versions
that are packaged for Node.js 16, which causes the publish workflow to
attempt to compile them from source. We're missing some of the libraries
necessary to compile the libraries from source, so this just ends up
failing.
Pinning to 10.x should fix the issue, and it's exactly what we're doing
for the CI workflow anyway.

Pin Node.js version to 10.x for release workflow.

---

app/App.tsx
app/components/listing/feedback/FeedbackForm.jsx
app/init.tsx
app/pages/OrganizationEditPage.jsx
app/pages/ServiceDiscoveryForm/ServiceDiscoveryForm.jsx
app/utils/location.ts

This PR adds a page's URL search query to page view tracking in Google Analytics. Ruochen asked for that here: https://docs.google.com/document/d/12IPTzG5y60StBQQdZ8_Jg9oR7N5pcom2Y3QQ85FTN3I/edit 
I also added a GA event to track when a user searches for a service with eligibility/category refinements per his request.
Finally, I added a second commit that disabled es-lint on our remaining console/alert statements to clean up our linting CI checks. Hopefully this is just a holdover until we devise a better solution. Perhaps we can add some kind of client side error tracking (maybe in GA itself?) rather than using console.log. If there's any logs we can just plain remove, let me know. I wasn't sure if we want to leave them for prod debugging or not.

Resource pathway tracking

---

app/components/edit/ProvidedService.jsx
app/components/listing/ServiceDetails.tsx
app/models/Service.ts

Eligibility used to be a text field on Service. It was later replaced
with a many-to-many relationship between Services and a dedicated
Eligibilities table, but a couple places in the askdarcel-web app still
read from the legacy field.
This removes the last instances of this older field.

Stop using legacy eligibility field.

---

app/components/search/Pagination/ResultsPagination.module.scss
app/components/search/Pagination/ResultsPagination.tsx

Hides "Add Org" button per Amanda's request. Fortunately it only exists in one component.

Hide Add Organization button per request from content team.

---

app/pages/ServiceDiscoveryForm/ServiceDiscoveryForm.tsx
app/pages/ServiceDiscoveryForm/constants.ts

We are adding a Long Term Housing tile which will have several steps on the form page, rather than the standard single step that other tiles have. (The single step for our other tiles is the client eligibilities checkboxes; the LTH will have 2-3 of these steps/checkbox groups). 
Before starting the LTH work, I wanted to convert the form page to typescript to make any changes to this file safer and easier. I'm branching off of this branch to do my LTH work

Service discovery form typescript

---

app/components/listing/MapOfLocations.tsx
app/components/listing/OrganizationDetails.tsx
app/components/listing/ServiceDetails.tsx
app/components/search/SearchResults/SearchResults.jsx
app/components/search/SearchResults/SearchResults.module.scss
app/components/ui/Translate.tsx
app/pages/OrganizationListingPage.tsx
app/utils/whitelabel.ts

Adds logic to the white label sites to enable/disable the Google Translate widget. Also adds translate=no attributes to HTML elements where we do not want translation to occur (addresses, org names, etc). Lastly, this adds a whiteLabelDefaults object with default props that are merged into all of our white label site objects.
Also this changes how layout is handled for services on the search result page – it replaces Flex with Grid
The first screenshot shows comparison between my local dev and Staging to demonstrate that mobile layout is the same after changing to grid. The second screenshot is of my local environment using grid on a standard desktop screen size.

1157 translation widget

---

app/components/ui/Translate.tsx
app/init.tsx
package-lock.json
package.json

* Enables `lang=` query param to specify a target translation language so SFFamilies portal site may link to the visitor's preferred language
This is done by overriding the (undocumented, as far as I can tell) `googtrans` cookie that the Google Translate widget inspects - this seems to be the only method out of other [suggested options to set a target language](https://stackoverflow.com/questions/1773687/google-translate-set-default-language/8493765#8493765) that works reliably.
Technically only the SFFamilies whitelabel is requesting this feature, but I think the language override could potentially be useful across sites. This shouldn't do anything if translation isn't enabled.
For example, with `lang=zh-TW`:
This session cookie should be scoped to the domain (and root + child paths):

Allow lang query param to translate sites

---

app/App.module.scss
app/App.tsx
app/components/Texting/Texting.module.scss

This is important for shorter screens (< ~700px), where the submit button on the Texting modal may not be visible.
This also adds a somewhat unrelated (though kind of related) fix to the Texting modal, where the Filters bar from the search results page was above the Texting modal along the z dimension. Forcing the main page and the modal to be in different stacking contexts fixes this issue and overall makes the stacking and scrolling a bit easier to reason about.
---
FWIW, the way I tested this was with Chrome's responsive mode, setting the resolution to 1024 x 600 px, since my display resolution is far taller than 600 px.

Allow Texting modal to be scrollable.

---

app/config.ts
app/utils/whitelabel.ts
cypress/e2e/organization_page.cy.ts
cypress/e2e/service_page.cy.ts
package-lock.json
package.json

Makes updates in reference to @richardxia 's helpful comments on https://github.com/ShelterTechSF/askdarcel-web/pull/1206
I updated Cypress from v10 to 12 which fixed an issue with caching the response to Cypress intercepts and negated a need for us to add a funky fix for that. Bumping the version caused a few of our tests to faill; we were using a `.should` after requests where we should have been using a `.then`. i'm not sure why this was done to begin with but it seemed like a pretty straightforward and reasonable change to make as part of this PR.
I also added an interface for our config object.

Update Cypress to v 12. Add TS interface to app Config const.

---

app/components/listing/feedback/FeedbackForm.tsx
app/hooks/APIHooks.ts
app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.tsx
app/utils/DataService.ts
package-lock.json
package.json

Refs #1175.
This migrates the APIHooks and DataService files over to TypeScript. There should be no functional change, as the only changes are to the type annotations. Some of the more notable changes include adding the `@types/lodash` package as a dependency and fixing a slightly incorrect type annotation `ServiceDiscoveryResults.tsx`, which was claiming that the argument are of type `CategoryRefinement`, but in reality, it is just `Category`, lacking the Algolia-specific fields that `CategoryRefinement` has.

Mmigrate APIHooks and DataService to TypeScript

---

app/components/ui/Translate.tsx
app/utils/whitelabel.ts

These are the minor changes that I suggested as a post-merge review comment in https://github.com/ShelterTechSF/askdarcel-web/pull/1225#pullrequestreview-1300787255.
- Change the spelling of the type to `readonly string[]`, which is equivalent
- Change the comment to a documentation comment, which allows it to show up on hover
- Remove an unnecessary nullness check, since the type cannot be null
Here's an example of what the documentation comments look like in my editor of choice (vim), but it should be similar in other modern editors:

Minor tweaks to whitelabel enabledTranslations property.

---

.eslintrc.js
.prettierignore
app/components/ucsf/Layout/Layout.module.scss
app/components/ucsf/Layout/Layout.tsx
app/components/ucsf/RefinementLists/EligibilityRefinements.tsx
app/components/ucsf/RefinementLists/SubcategoryRefinements.tsx
app/components/ucsf/RefinementLists/ucsfEligibilitiesMap.ts
app/pages/UcsfDiscoveryForm/UcsfDiscoveryForm.module.scss
app/pages/UcsfDiscoveryForm/UcsfDiscoveryForm.tsx
app/styles/utils/_layoututils.scss

This PR adds code to select "See All" checkboxes by default on the UCSF Discovery Form page, per product discussion -- the eligibility and subcategory refinements state vars are initialized with a hash that has all See All refinements selected. 
This PR also implements floating buttons on the UCSF Discovery Form page per the [Figma designs](https://www.figma.com/file/HUTUyVuJf8lctj5fAFIY32/UCSF?node-id=5626%3A10024&t=pdo86f0CTBULiX2V-0) and product discussion.

Ucsf UI improvements

---

.github/workflows/ci.yml
package.json

I noticed that Prettier doesn't seem to actually be checked in CI, since `npm run lint` only runs ESLint, not Prettier. This adds new `prettier` and `prettier:fix` scripts to our package.json, and then it adds `npm run prettier` to our CI job.

Run Prettier in CI.

---

.eslintrc.js

This was caused by several PRs merging while the PR that turned on Prettier in CI was in flight.

Fix Prettier errors.

---

app/components/edit/FormTextArea.tsx
app/components/ui/PopUpMessage.tsx
app/pages/OrganizationEditPage.tsx

Refs #1175.
This deals with some of the lower-hanging fruit on the Edit Page, where either the type is totally known due to the values coming purely from the frontend (as opposed to the backend API), such as event handlers or `setState()` being called with known keys on the object. Notably, this adds a type for the props of the main page component as well as one for the state of that component, though the current version of the state type definition has a lot of `any`'s in it.
I've been cautious about not using the types defined in `app/models` until I can confirm that they actually match the Edit Page, since the `app/models` types mostly reflect what the API sends back, but the Edit Page performs a lot of transformations internally. For now, leaving the types as `any` or even …

Migrate Edit Page to TypeScript Part 2

---

app/components/edit/ProvidedService.tsx
app/pages/OrganizationEditPage.tsx

Refs #1175.
This is the next unit of work I've done in terms of migrating the Edit Page to TypeScript. Here, I've defined types for the internal versions of Schedule, ScheduleDay, Organization (Resource), and Service, which differ from the versions that the API endpoints respond with. I won't detail the differences in this PR description, but I wrote comments next to the type definitions explaining the differences. The short summary is that the Edit Page has to keep track of certain state in its UI, so it can't maintain that state using the exact same shape of the data as stored in the DB.
These internal data type aren't great, and if I were to rewrite this page from scratch, I would do it very differently, but I am glad that TypeScript has allowed me to at least annotate exactly what …

Migrate Edit Page to TypeScript Part 3

---

app/components/edit/EditServices.tsx
app/components/edit/EditSidebar.tsx
app/pages/OrganizationEditPage.tsx

Refs #1175.
This is the next chunk of work I've done to increase type strictness on the Edit Page. Most of these changes revolve around the Service type, which I actually had to split into three separate types (not including the one that already exists in `app/models/`!).
The complexity of the types is a reflection of the complexity of the code, and although this could probably be simplified in the future, I tried to make as few functional code changes as possible while adding type annotations to this code.
_Warning: there's a huge wall of text ahead, so apologies for not being able to describe these changes more succinctly._ I won't hold it against you if you don't read the rest of this PR description, and it might even be easier to review this PR if you start with the actual code diff …

Migrate Edit Page to TypeScript Part 4

---

app/App.tsx
app/config.ts
app/pages/ServiceDiscoveryForm/ServiceDiscoveryForm.tsx
app/pages/UcsfDiscoveryForm/UcsfDiscoveryForm.tsx
package-lock.json
package.json

Our `react-ga` package [has no plans to support the new GA 4 property](https://github.com/react-ga/react-ga/issues/460), so I needed to use a package that does. Come July when Google sunsets its UA tracking ,we can remove the `react-ga` package and its references.

Add GA4 Google Analytics tag to tracking code

---

app/components/edit/EditServiceChildCollection.tsx
app/components/edit/ProvidedService.tsx
app/models/Service.ts
app/pages/OrganizationEditPage.tsx

Refs #1175
Major Edit: The original version that I submitted as a PR here was incorrect and was causing the Edit Page to completely break. I've pushed up a new version to this branch, and I've rewritten this PR description to reflect the new changes.
This adds TypeScript type annotations to the ProvidedService component.
In order for the types to validate, this required modifying the definition of InternalFlattenedService to make the `schedule` property required. This appears to be true in practice, where either the `schedule` property is defined by the original API response, or it gets set by the frontend code when creating a new Service, so there shouldn't be a case where it is undefined.
This adds an additional runtime check to the `applyChanges()` method to assert that the final, …

Migrate Edit Page to TypeScript Part 5

---

app/components/edit/EditServiceChildCollection.tsx
app/components/edit/EditSidebar.tsx
app/components/edit/ProvidedService.tsx
app/models/Service.ts
app/pages/OrganizationEditPage.tsx

Built this out as a way to test https://github.com/ShelterTechSF/askdarcel-web/pull/1247 changes and to fix something that's been in the backlog.
Displays activate button if resource has been deactivated and enable re-activating a resource. 
I also made a couple small TS changes to the handleDeactivate function for greater type specificity. Let me know if they get in your way all and ill revert them.

Expose activate function on edit page when resource is deactivated

---

app/components/ui/Banner.module.scss

Changing the property `align-items: unset` in the mobile view top aligns the icon. However, if this is not the best implementation I will take a look at the resource provided again.

Unset banner content alignment in mobile view

---

app/components/edit/EditServiceChildCollection.tsx
app/components/edit/EditServices.tsx
app/components/edit/ProvidedService.tsx
app/pages/OrganizationEditPage.tsx

Refs #1175.
The new type for `handleChange()` requires that:
1. the field name actually matches the name of a real field on the InternalTopLevelService type, and
2. the type of the new value matches the type of the field on the InternalTopLevelService type.
This gives us much stricter type checking, since different fields of InternalTopLevelService have very different types, and this allows us to actually check those types against the values that we are passing in.
Several of the other changes in this commit are to pass type checking, now that we're more strictly enforcing calls to `handleChange()`. Two notable changes are that we've removed the `propertyKeyName` prop to `EditServiceChildCollection`, since it can be baked into the `handleCollectionChange` function, and slightly changing …

Edit Page: Add strict type for ProvidedService's handleChange() function.

---

app/components/listing/ActionBar.scss
app/pages/ServiceListingPage.tsx
app/styles/components/_listing-page.scss

Looking at the large side icons on listing pages finally drove me crazy, so I dug up an old [Figma design](https://www.figma.com/file/0X2KzS0qDEfZPRRm0TQyd5/SFSG-Website?type=design&node-id=1458-235&t=8TEfnDAk8dkge9k9-0) and updated the styles. There are many more differences between the design and our current listing page (and I don't know how current it is), but I find the side icons size to be so noticeable that I'd like to quickly fix them.
I also fixed a UI bug where the service description margin wasn't aligning with the service title (too far to the left, see example below):

Adjust listing page side icons to more closely match figma designs

---

app/components/ui/Footer.scss
app/components/ui/Footer.tsx
app/pages/OrganizationListingPage.tsx
app/pages/ServiceListingPage.tsx
app/utils/whitelabel.ts

Our415 has requested that we add the City of San Francisco seal as a footer on their listing pages. (They don't want any of the other stuff on there, like links to ShelterTech social media.) Verified default whitelabel looks the same on home page and listing pages.
As for Our415:

Add SFSeal footer to Our415, allow configuring whitelabel footer options

---

app/components/edit/EditNote.tsx
app/components/edit/EditNotes.tsx
app/pages/OrganizationEditPage.tsx

Refs #1175.
This is a mostly straightforward change to add strict type annotations to anything related to editing notes. There were some surprising things discovered from adding strict types, mostly involving the direct mutation of objects that should not be mutated in React. We leave this behavior in for now, but with comments describing what should eventually be fixed.

Edit Page: Add type annotations to EditNotes.

---

app/components/edit/EditSchedule.tsx
app/components/edit/EditScheduleDay.tsx
app/components/edit/ProvidedService.tsx
app/pages/OrganizationEditPage.tsx
app/utils/time.ts

Refs #1175.
This adds type annotations to EditSchedule and related components on the Edit Page. It doesn't add any new types, but it loosens a few types in existing places to account for nullness, which the code already safely handled before.

Edit Page: Add type annotations to EditSchedule.

---

app/components/edit/EditCollection.tsx
app/components/edit/EditPhones.tsx
app/pages/OrganizationEditPage.tsx

Refs #1175.
This adds type annotations to the EditPhone component as well as the editCollectionHOC function. Note that there are some things in editCollectionHOC that cannot be correctly typed, since it appears to be incorrectly calling `setState()`, passing in the array of collection items rather than an object with a `collections` field. We leave the existing code alone, since it may be a little bit of work to untangle the technical debt, but we at least add stronger type annotations to everything around it.

Edit Page: Add type annotations to EditPhone and EditCollection.

---

app/components/ui/Footer.tsx

The Footer pointed to the old Volunteer page, which we redesigned and gave a new URL a few years ago.

Fix Volunteer link in footer.

---

app/components/edit/EditAddress.tsx
app/components/edit/EditServices.tsx
app/components/edit/ProvidedService.tsx
app/models/Meta.ts
app/pages/OrganizationEditPage.tsx
tsconfig.json

Refs #1175.
I feel like I'm finally getting close to the end here. This should be the last subcomponent of the Edit Page that needs type annotations, and I think the bulk of the remaining missing type annotations are all on the top-level OrganizationEditPage itself.
This PR is a bit bigger than the last several that I've submitted. There were a couple refactoring changes I made before actually adding type annotations to the code:
- 129159041b8c73eb9afbeeacb389c89b302b015a removes the `country` field from the `Address` type. We had actually removed this field from the API side while working on the Multiple Addresses project in https://github.com/ShelterTechSF/askdarcel-api/pull/586, since it was confusing to users on the edit page, and [we left some vestiges of it on the …

Edit Page: Add type annotations to EditAddress

---

app/pages/ServiceDiscoveryForm/constants.ts

Internet subcategories have been added to Staging and Prod via Rails console (https://www.sfserviceguide.org/api/categories/subcategories?id=1000007)

1271 add subcategories step to internet tile pathway

---

app/components/edit/EditSidebar.tsx
app/pages/OrganizationEditPage.tsx

Refs #1175.
I think this will be the penultimate PR for the Edit Page TypeScript migration. This adds type annotations everything except for the code path for editing existing Resources. Specifically, this fixes up some `any` types on the EditSidebar component, it adds type annotations to some generic utility functions (e.g. `deepClone()`), and it adds type annotations to the code that's called when creating a brand new Resource.
After this is merged, I think I should be able to do the last set of changes all in one shot.

Migrate Edit Page to TypeScript Part XII

---

app/models/Service.ts
app/pages/OrganizationEditPage.tsx

Refs #1175.
This should be the last major PR to migrate the Edit Page over to TypeScript. This goes through the last remaining functions in the OrganizationEditPage and adds type annotations to them. There were a number of weird things that I hit, but I hope most of the inline comments are self-explanatory.
One thing to note is that most of the `postServices()` is basically unsalvageable, since we start with an object of type `InternalService`, and we gradually morph and delete properties off of it until we get an object that looks more or less like `Service`, the type that represents what the API sends to the frontend app upon a GET request. There's no way for TypeScript to handle this because the object is in an intermediate state during the entirety of the transition. As such, I …

Migrate Edit Page to TypeScript: Final

---

app/components/Texting/Texting.tsx
app/components/Texting/components/FormView/FormView.tsx
app/components/Texting/components/FormView/Heading.tsx
app/components/search/SearchResults/SearchResults.jsx

When looking to convert the SearchResults file to TypeScript, I noticed that our Texting component does not support texting Resource info. This is deceptive as the "text me the info" link is displayed on Resource search listings. Thus, I've created a PR to fix this before getting back to migrating the SearchResults page, which I plan to do prior to making some changes to it as part of some UCSF work. See corresponding API PR [here](https://github.com/ShelterTechSF/askdarcel-api/pull/719)

Fix texting component to allow texting Resource info

---

app/components/edit/EditPhones.tsx
app/components/edit/ProvidedService.tsx
app/components/ui/WeGlot.tsx
app/pages/OrganizationEditPage.tsx
tsconfig.json

I had temporarily disabled this setting in https://github.com/ShelterTechSF/askdarcel-web/pull/1230 in order to make the TypeScript migration of the Edit Page easier. Now that the Edit Page has been fully migrated to TypeScript, we can re-enable this setting.
There were a handful of places where I needed to add explicit type annotations in order to make this pass again, but they were relatively straightforward to fix. Note that one of the fixes was to the WeGlot component, which was code added after I had disabled `noImplicitAny`.

Re-enable tsconfig `noImplicitAny`

---

app/components/search/SearchResults/SearchResults.tsx

This is causing CI to fail on the `master` branch because https://github.com/ShelterTechSF/askdarcel-web/pull/1282 added this code and https://github.com/ShelterTechSF/askdarcel-web/pull/1283 increased the strictness of the type checker, but because the two merged in parallel, neither change failed in CI.

Add missing type annotation in SearchResults.tsx.

---

docker/tiller/templates/askdarcel-web.conf.erb
webpack.config.js

Maybe not the long term plan, but for now we can consider routing to `api/v2` to hit the Go backend.  If we want to migrate any routes from the web app, we can add that `/v2` path param.

feat: add v2 route for separate backend service config

---

app/styles/components/_listing-page.scss

Fixes #1290. Note that in the ticket description, I had incorrectly stated that we weren't rendering Markdown for Service descriptions. The actual culprit was some missing CSS for Service descriptions.
The Organization descriptions had [a snippet of CSS](https://github.com/ShelterTechSF/askdarcel-web/blob/7d3f829ba04c0884a119b0433d06ced2c20ebd0c/app/styles/components/_org-page.scss#L86-L90) to add top-margin to all `<p>` elements, but the Service descriptions lacked this CSS, which caused consecutive paragraphs to have too little space between them. This adds the same spacing to the Services.
**Before**
**After**

Organization Page: Add margin to service description paragraphs.

---

.eslintrc.js
app/components/edit/EditCollection.tsx
app/components/edit/EditSidebar.tsx
app/pages/OrganizationEditPage.tsx

We had disabled some ESLint rules for our TypeScript code when we were initially migrating the codebase. These should no longer be necessary, so they have been removed, and the remaining failures have either been fixed or ignored at the line level.

Remove ESLint waivers for TypeScript code during transition.

---

app/components/search/Refinements/RefinementListFilter.tsx
app/components/search/Sidebar/Sidebar.tsx
app/components/ucsf/RefinementLists/ucsfEligibilitiesMap.ts
app/utils/whitelabel.ts

This expands the refinement limit value that we pass to the Algolia search component, if we are filtering out returned refinements – in cases where we are using `transformItems` to filter the returned refinements, we want the limit to be high to ensure that Algolia returns all of the refinements that we actually want to display. It's a little bit complicated, so I tried my best to explain it in comments. Let me know if this can be improved at all.
Tl;dr: Algolia passes back a limited amount of eligibility or category refinements. We have been filtering this returned list in some cases, without realizing that the original, unfiltered list may not even contain all of the refinements that we want to display. That's why sometimes the list on the sidebar can be very short.

Refinements fix

---

app/pages/ServiceDiscoveryForm/constants.ts

I think I said that UCSF wanted the refinements order switched on the sidebar during our product/dev meeting, but indeed it was actually in the discovery steps (brain fog). Fortunately that was a much easier change to make.

1274 Show service type/categories first in UCSF discovery steps

---

app/components/search/Sidebar/Sidebar.tsx
app/components/ucsf/RefinementLists/ucsfEligibilitiesMap.ts
app/models/SearchHits.ts
app/pages/ServiceDiscoveryForm/constants.ts
app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.tsx
app/pages/UcsfDiscoveryForm/UcsfDiscoveryForm.tsx

UCSF asked us to order our sidebar subcategories by a defined order that they sent us. Our CategoryRelationship table has a "child_priority_rank" field that I set for the child categories returned by our `Ucsf-ipv` parent category. I then use this order to sort the categories returned by Algolia.
This PR also removes some of the static eligibilities from the IPV constant eligibility list defined on the f/e. These eligibilities are not used for now. Speaking of which, maybe we should create a CategoryEligibility table similar to the CategoryRelationship table that will allow us to define eligibilities to be associated with a given parent category in the DB.

1274 ipv subcategory sort

---

.github/workflows/ci.yml
app/models/Service.ts
cypress/e2e/service_page.cy.ts
docker-compose.test.yml
docker/templates/default.conf.template

This would flip all GET services by ID to use Go server.
Will discuss with team before any action on this.

Use v2 API route for GET services by ID

---

app/components/ui/NewsArticles/NewsArticles.tsx
app/pages/EditBreakingNewsPage.scss
app/pages/EditBreakingNewsPage.tsx

This ticket fixes issues with the edit page UI here is the [ticket](https://github.com/ShelterTechSF/askdarcel-api/issues/730)
We need to merge these [API changes](https://github.com/ShelterTechSF/askdarcel-api/pull/731) before this PR.

Edit Page Enhancements

---

app/Router.tsx
app/components/utils/PublicRoute.tsx
app/components/utils/index.ts
app/pages/AuthInterstitial.tsx

Mostly to fix an issue where the user session init code was being run twice and breaking the log-in flow. it was only happening on prod for some reason. this should patch it at least. Also added a public route component to redirect authed users navigating the the log-in/sign-up pages

Prod auth bug fix

---

docker-compose.yml

This environment variable was set in the CI docker-compose.yml file, but not the development one. Setting it in the development one makes the Go API work seamlessly with the development docker-compose networking setup.

Add `API_GO_URL` to development docker-compose.yml.

---

app/pages/NavigatorDashboard/NavigatorDashboard.tsx

Since we haven't filled out the `PARENT_ELIGIBILITIES` variable yet, the current logic keeps trying to fetch the child eligibilities for them, setting the `eligibilities` state variable to the empty array over and over again. If we actually set values for the `PARENT_ELIGIBILITIES`, then this wouldn't be a problem, but for now, guard the actual calling of `setEligibilities` to avoid infinite rerendering.

NavigatorDashboard: Fix infinite rerender bug.

---

app/utils/AuthService.ts

We're still hitting issues in prod related to authentication, and adding logging around the `passwordlessLogin` function and the state tokens will help us debug it.

Add more logging statements around authentication.

---

app/utils/AuthService.ts
app/utils/useAppContext.tsx

We have two different notions of user IDs: one from Auth0, which is a string and is contained in the JWT, and one from our own API, which is an integer. This renames the `id` field within the auth state to `externalId`, to make it clearer that these are from the identity provider.
I wanted to split this off from a much larger PR I'm making, since this is kind of important on its own, and I didn't want it to get lost in the noise.

[AuthService] Rename Auth0-specific ID field.

---

app/utils/refinementMappings.ts

The refinement mappings are a hardcoded list of eligibility and category names used for the left sidebar filters on the search results page (but not the tile results page). This list has been neglected, and various eligibilities and categories have been renamed or deleted from the database. This commit updates the names based on feedback and advice from the Content team, even though some of these even predate the Content team.
I validated these changes by copying and pasting these hashes/objects/maps into the Rails console and double checking that all of these correspond to an Eligibility/Category with the exact same spelling.
This is also somewhat validated by the search results page actually allowing all of these checkboxes to be checked, since the widget normally disables a checkbox if …

Fix outdated names in refinement mappings.

---

app/components/search/Header/Header.module.scss
app/components/search/Header/Header.tsx
app/models/SavedSearch.ts
app/pages/NavigatorDashboard/NavigatorDashboard.tsx
app/pages/SearchResultsPage/SearchResultsPage.tsx

This hooks up the placeholder locations in the Navigator UI with the saved search APIs.
When a user is logged in, we add a "Save Results" button to the search results page, and pressing that button will fire an API request to save the current search filters and query to the database. This involved pulling out the pieces of the search state object that Algolia's InstantSearch API manages into the format our API accepts.
On the main dashboard page, we perform the reverse operation, querying our API for saved searches, and then reconstituting a simulacrum of the serach state object, solely for the purposes of generating the URL query parameters directly from that object, which is how the search results page normally works.
Since I made some small UI changes, here's a screenshot showing what …

Hook up saved search APIs.

---

auth0/README.md
auth0/passwordless-email-template.liquid

I wanted to add these to version control so that it's easier to track, even if we have to manually sync them to Auth0 through their portal.
Two things that this doesn't include:
1. The SFSG logo image URL is actually broken, since we don't have stable URLs for our assets. Our webpack config appends a hash to the names of assets, which is a cache-busting strategy so that you don't have to worry about clearing them from a CDN when you deploy. (Ironically, our bundle.js file itself does _not_ have the hash, which is why we sometimes have to manually clear the Cloudflare CDN anyway on deploys...) I think I'll create a separate PR to make a copy of this image and set up webpack to not append the hash, which should provide a stable URL for emails.
2. Our production Auth0 tenant's email template …

Add Auth0 email template.

---

auth0/passwordless-email-template.liquid

The original placeholder width of 50 px is way too small for our logo, which is very wide and short. Setting it to 200 px looks better.

Increase logo size in email.

---

app/components/ui/BookmarksMenu/BookmarksMenu.tsx

Without adding this logic, the BookmarksMenu will not reflect any new bookmarks that are added unless you refresh the browser. The reason is because the menu is always mounted, as it lives at the `App` layer, though hidden off screen. This means that the `useEffect()` call only happens once, when the app is first loaded.
By capturing the `isOpen` variable in the `useEffect()`'s dependency list, we can retrigger the `useEffect()` call whenever the menu is opened, causing it to be updated with the latest state of the user's bookmarks.
I missed this during local development, since prior to me moving the dashboard page to the `/` route, I had to manually type in the URL of the dashboard page to get back there. This effectively forced a page refresh, causing the app to be loaded from scratch, …

Refresh BookmarksMenu when it is opened.

---

.github/workflows/ci.yml
README.md

Docker apparently moved the standalone `docker-compose` command into a subcommand of the `docker` command, and they deprecated the standalone command. GitHub Actions recently updated to a new enough Docker version that dropped the standalone `docker-compose` command, which is causing CI to fail.
This updates both the CI configuration as well as our README to only use the subcommand version.
See https://github.com/orgs/community/discussions/116610

Switch from `docker-compose` to `docker compose`.

---

app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.tsx
app/utils/whitelabel.ts

In order to surface some specific results on the tile results page, we make use of an optional filter on a newly added Algolia index property.
On the backend, we've created a new column, `boosted_category`, which we can optionally set on each Service. This allows us perform an optional filter only on the tile results pages, and not the general search page, where services that match the optional filter are boosted in ranking.
For now, there can only be one `boosted_category` per service, but this is sufficient for the current use case, where only two services need to be boosted, and they each only apply to one category.

Boost service discovery (tile) results based on boosted category.

---

app/utils/useAppContext.tsx

refs https://github.com/ShelterTechSF/askdarcel-web/issues/1391

Reset app auth state if Auth0 session has expired

---

.github/workflows/ci.yml

Github deprecated v2 of their upload-artifact action, which we were using. This updates it to v4.
CI was failing. See: https://github.com/ShelterTechSF/askdarcel-web/actions/runs/11751183980/job/32741450392
And: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Fix github CI action

---

app/components/edit/EditCollection.tsx
app/components/edit/EditNote.tsx
app/components/edit/EditNotes.tsx
app/components/edit/EditScheduleDay.tsx
app/components/edit/EditServices.tsx
app/components/edit/EditSidebar.tsx
app/components/listing/MapOfLocations.tsx
app/components/listing/ServiceDetails.tsx
app/components/search/SearchMap/SearchEntry.tsx
app/components/ui/BookmarkModal/BookmarkModal.module.scss
app/components/ui/BookmarkModal/BookmarkModal.tsx
app/components/ui/BookmarksMenu/BookmarksMenu.tsx
app/components/ui/NewsArticles/NewsArticles.tsx
app/pages/NavigatorDashboard/NavigatorDashboard.tsx
app/pages/ServiceDiscoveryForm/ServiceDiscoveryForm.tsx
app/styles/utils/_helpers.scss

Something appears to have changed about the Material Icons icon font that we're loading from Google Fonts, which is making them render strangely. Most severely is that on iOS, the width of the element containing the icons is 1,000,000 pixels wide, which not only stretches the page but also blocks click events from going through, even though the element itself is transparent. On desktop and Android, we do not see the extremely wide icons, but it appears that the icons are noticeably smaller than they used to be.
Several years ago, Google released [Material Symbols](https://m3.material.io/blog/introducing-symbols) as a successor to Material Icons. Switching our app to Material Symbols appears to get rid of the issues described above.
Note that there are slight differences in the icons after …

Fix Material Icons by migrating to Material Symbols.

---

.github/workflows/ci.yml
.github/workflows/publish-qa.yml
.github/workflows/publish-release.yml

The actions/cache@v2 action was deprecated (https://github.com/orgs/community/discussions/148746), and now our builds aren't running. This upgrades us to the newest version, v4, and it also upgrades all other actions to their latest versions just to get it over with.

Upgrade versions of actions in GitHub Actions.

---

app/components/ucsf/RefinementLists/ucsfEligibilitiesMap.ts

UCSF would like to add this to the second page of DC-Nav's Intimate Partner Violence form, which lists service eligibilities in the form of patient demographics. Our actual internal eligibility name is "African/Black", but they would like it to be displayed as "Black/African American", so we make use of the `alias` field to rename it in the UI.

DC-Nav: Add African/Black eligibility to IPV category.
