.travis.yml
Dockerfile
docker/tiller/common.yaml
docker/tiller/templates/askdarcel-web.erb

Some slight reorganization of the build output might make some of this clearer. Served resources show up in three different places in the repository: `./build/public`, `./assets`, and `./index.html`.

Build a Docker image after CI and push it to Dockerhub.

---

.gitignore
app/components/Resources/Map.js
app/components/Resources/ResourcesTable.js
app/init.js
app/utils/config.example.js
app/utils/config.js
app/utils/google.js
package.json
webpack.config.js

* The API key for google maps is git ignored, but now loads
* Only 9 resource results show at a time, can navigate with Next and Previous buttons

Fixes #41, Fixes #42

---

app/components/Resources/ResourcesTable.js

Switch name with description, use log desc by default

---

app/components/Resource/Resource.js

Replace the placeholder with actual info

Add descriptions to resource page

---

app/components/Header.js

window.location.reload(); is janky, looking for better ways to refactor that behavior

Search fixes

---

app/components/Resource/ResourceInfos.js

If someone could verify, that would be great. Having trouble hitting the backend.

Fix href for website.

---

app/components/CategoryPage.js

Depends on remove_image_path PR in api

Remove image_path from categories call

---

app/components/Resource/ResourceInfos.js
app/components/Resources/ResourcesTable.js
app/utils/config.example.js
app/utils/google.js

Not ideal but we need this for now to fix behavior.

Temporary google API fix tweak

---

app/init.js
app/reducers/index.js
app/reducers/resourceReducer.js
app/router.jsx
app/store/configureStore.dev.js
app/store/configureStore.js
app/store/configureStore.prod.js
package.json
webpack.config.js

Added Redux to the project and plan on converting a few components to Redux today

redux added to project!

---

app/components/Resource/ResourceInfos.js

fixed with regex

---

app/components/App.js
app/components/Resource/Resource.js
app/components/Resource/ResourceMap.js
app/components/Search/ResourcesMap.js
app/components/Search/ResourcesTable.js

This is my first attempt at trying to do something in React that's more than just editing minor UI things, so please let me know how I should do things correctly in React.
Previously the user location was being checked in multiple places separately:
- the top-level App component
- the Search/ResourcesTable component
- the Resource/ResourceMap component
I moved it all to the the App component and passed it all the way down to both the other components, but I had to mess around with the state vs. props setting a bit in order to get it to work correctly without running into an infinite loop. I'm not too familiar with how asynchronous state updates should get passed down, but what I did was update the state at the top level and pass the location to subcomponents as props and it seems to work …

Pull user location checks to App component and add bounds check.

---

app/components/Resource/DetailedHours.js
app/components/Resource/Hours.js
app/components/Resource/ResourceInfos.js
app/components/Resource/Services.js
app/styles/components/_org-page.scss
app/utils/index.js

Added hours and service details to each service on resources

---

app/components/Resource/DetailedHours.js
app/components/Resource/Hours.js
app/components/Resource/Resource.js
app/components/Resource/ResourceInfos.js
app/components/Resource/Services.js
app/styles/components/_org-page.scss
app/styles/st-base/_typography.scss

The resource page now resembles the new design from the latest invision mocks found here: https://invis.io/8693TIG3K#/228639026_resource
Resolves #169 #219
Outstanding issues include:
* a bug with the today's hours saying "Closed Now" #184 
* services do not display updated date stamp or category #220
* icons in the info section are not to spec #102 
* button styling in the right aside are not to spec #220
* multiple hours on the same day look like duplicate days (remove "Monday Monday" from weekly hours list #220
* the map is very zoomed out and should be closer to the pin location #220
* service hours and resource hours are the same #165

Redesign of the resource page to match designs from invision

---

.eslintignore
.travis.yml
app/assets/index.js
app/components/Loader.js
app/components/Navigation.js
app/utils/config.example.js
package.json

I added a few more files to the set of linted files and cleaned up their code style. I also added an `npm run lint` script to make it easier to manually lint.

Lint more files

---

app/components/Admin/ChangeRequests.js
app/styles/components/_admin.scss

Added resource ID to every change request to make it easier for datathon participants to reference issues

---

app/components/Resource/Resource.js
app/components/Search/ResourcesTable.js

Verifying that this solves authentication issue, if so then I will update rest of application to do this.

fix(cookies): send cookies with API calls to work with auth

---

app/components/Edit/EditServices.js
app/components/Edit/MultiSelectDropdown.js
app/components/Resource/Services.js
app/styles/components/_edit.scss

Allows for users to select from a pre populated list of eligibilities rather than a free from input (similar to how categories already works).
**Blocked:** Waiting on BE to support the post request.

Support for multi select eligibility 

---

app/components/App.js
app/utils/index.js

- Created rounding function based on a blog post about rounding in JS (http://www.jacklmoore.com/notes/rounding-in-javascript/)
- Rounded functions to the fourth decimal place when retrieved from geolocation

Issue #321: Trim coordinates being sent api on user's location

---

app/components/Edit/EditSections.js
app/components/Edit/EditServices.js
app/styles/components/_edit.scss
app/utils/DataService.js

Added the ability to deactivate both resources and services via the edit pages

Deactivation functionality

---

app/components/Edit/EditPhones.js
app/components/Edit/EditSections.js

followed rxia's recommendation for removing the Phones Add button from the edit page

proper removal of phones add button

---

app/components/Admin/Admin.js
app/components/Navigation.js

- increases performance
- allows for caching of API requests
- prevents user's location from being recomputed

Issue #175: Replace a-tags with Link-tags

---

app/components/Edit/EditCollection.js
app/components/Edit/EditSections.js
app/styles/components/_edit.scss
app/styles/st-base/_typography.scss

Adds the ability to remove phone numbers from the edit page

Delete phone functionality 

---

app/components/Edit/EditNotes.js
app/components/Edit/EditSections.js
app/styles/components/_edit.scss

Adds the ability to delete notes from the edit page. 
TODO: Still needs some design love

Delete Note 

---

.eslintignore
app/components/Edit/EditSections.js
app/components/Edit/EditServices.js
app/components/Edit/FormTextArea.js
app/components/Edit/ProvidedService.js

- break out into several reusable components
- fix tabing/spacing
- use updated ES6
- remove unused methods

Issue #386: Refactor EditServices to conform with coding standards

---

app/components/Edit/EditSections.js
app/components/Edit/ProvidedService.js

Made it so front end passes back phone numbers upon resource creation. 
Still need to ensure back end can support the formatting of the phone numbers in the payload:

Fix for phone numbers on resource creation

---

app/styles/components/_org-page.scss

Change resource description CSS to honor line breaks

---

app/components/Edit/ProvidedService.js

Fixes for edit service

---

package-lock.json
package.json

Used Husky (https://github.com/typicode/husky/tree/master) to implement precommit linting
Fixes #448

Issue #448: Add pre-commit hook to run "npm run lint" before commiting

---

app/init.js
package-lock.json
package.json

It's crazy that we have no idea who is using AskDarcel, GA account created under my Sheltertech email and can share it with anyone who wants access.
Should probably add the same for Sheltertech.org

Added Google Analytics to the page, only in prod mode

---

app/components/Edit/EditSections.js
app/components/Edit/EditServices.js
app/components/Edit/EditSidebar.jsx
app/components/Edit/ProvidedService.js
app/components/Resource/Resource.js
app/styles/components/_all.scss
app/styles/components/_edit.scss

- Creates sidebar component
- Closes #450

Issue #450: Add new sidebar to edit page

---

app/components/Edit/EditSections.js
app/components/Edit/EditSidebar.jsx

Fixed bug when resource doesn't exist (e.g. new resource page)

---

app/components/Edit/EditSections.js
app/components/Edit/ProvidedService.jsx

- Resource: alternate_name, legal_status
- Services: alternate_name, interpretation_services, url, wait_time
Closes issue #403 
Dependent on [askdarcel-api #293](https://github.com/ShelterTechSF/askdarcel-api/issues/293)

Issue #403: Add new data fields

---

README.md

This just updates the Docker setup instructions, since I think you guys are changing the non-Docker flow.

Add instructions for populating the .env file.

---

app/components/listing/ActionSidebar.jsx
app/pages/Service.jsx
testcafe/pages/ServicePage.js
testcafe/service.js

TestCafe: Add ServicePage and basic Service test

---

app/components/Edit/EditSections.js

After creating new resource, the page redirects to it. Closes #485

Redirect New Section Creation

---

.eslintrc.js
app/init.jsx
package.json
webpack.config.js

process.env.NODE_ENV no longer worked for some reason, manually added NODE_ENV to fix google analytics tracking.

Fixed google analytics in prod

---

app/pages/OrganizationListingPage.jsx
app/pages/ServiceListingPage.jsx

In addition to the organization page, I've also updated the service listing page to protect against missing addresses. I just added some conditionals and pulled some logic out of the jsx and into methods.

Fix organizations/resources without addresses, closes #476

---

app/components/listing/Services.jsx

Add service website link to organization page #571

---

app/components/search/CustomSearchHits.jsx
app/components/search/ResourceEntry.jsx
app/components/search/SearchMap.jsx
app/components/search/SearchRow.jsx
app/components/search/SearchTable.jsx
app/components/search/ServiceEntry.jsx
package-lock.json

Adds numbers to the map and search table so you can tell where a service/resource resides on the map.

Map numbering

---

testcafe/editResource.js
testcafe/pages/EditPage.js
testcafe/pages/ResourcePage.js

Issue #437: Confirm adding/deleting a service works

---

testcafe/pages/EditPage.js
testcafe/pages/ServicePage.js
testcafe/service.js

Issue #439: TestCafe tests for add/remove service schedule

---

app/components/ui/Navigation.jsx
app/components/ui/Navigation.scss

There are only two live links at the moment. I've only included live links in this PR

598 new desktop header

---

app/components/ui/LandingPageEligibilityBlock.jsx

Same thing as https://github.com/ShelterTechSF/askdarcel-web/pull/629 but for the landing page's eligibility blocks.
Have not fully tested locally, since there aren't any eligibilities with special characters in the development DB, but I'm pretty sure this will work.

Escape query params for eligibility block as well.

---

app/components/layout/FindHeader.jsx

dynamically pull in resource count

---

app/components/ui/LegalBlockConfig.js

Change copy Housing -> Housing Advocacy in Legal Block

---

app/pages/HomePage.jsx

swap legal and basic needs blocks on homepage (#644)

---

app/assets/index.js
app/components/App.jsx
app/components/ui/Footer.jsx
app/utils/whitelabel.js
package-lock.json
package.json

This PR pulls in the [react-helmet](https://github.com/nfl/react-helmet) library, which makes it really easy to add things to the `<head>` tag including the `<title>` as well as various metadata tags. For now, this just sets the title based on whether the MOHCD domain is present. Here is a screenshot that proves that it works for me locally when I set the `MOHCD_DOMAIN` config variable to `localhost`.

663 Set dynamic page title

---

.eslintignore
app/components/App.jsx
app/components/maps/MapOfLocations.jsx
app/components/ui/Navigation.jsx
app/pages/HomePage.jsx
testcafe/editResource.js
testcafe/listings.js

I'm gradually working through the app fixing up lint errors and removing files from `.eslintignore`.
Main files touched are:
- App.jsx
- MapOfLocations.jsx
- Navigation.jsx
- HomePage.jsx

Fix more lint errors

---

app/pages/OrganizationEditPage.jsx

https://github.com/ShelterTechSF/askdarcel-web/issues/482

(#482) Allow deletion of organization fields

---

.eslintignore
app/components/listing/Notes.jsx
app/pages/OrganizationListingPage.jsx

I'm about to implement the resource page redesign, and figured I'd start by enabling linting on this file. This PR looks like a bigger change than it is. All I've done is enabled linting on this file, fixed some places where we should have been using destructuring and fixed the indentation.
Also added some react keys to the notes list to get rid of a console error.

Enable linting on Organization Listing page

---

app/components/edit/EditAddress.jsx
app/pages/OrganizationEditPage.scss

see https://github.com/ShelterTechSF/askdarcel-web/issues/191

add no location checkbox to edit form

---

app/components/ui/Navigation.jsx

Navigation.jsx - Replaced 'About Us' link with 'Help' link

added help link

---

app/components/ui/Footer.jsx

The new link points to our Google Form titled "SF Service Guide
Feedback". This is the same Google Form link that currently appears in
the Intercom dialog.

Add "Submit Feedback" link to footer (#707)

---

app/components/ui/LegalBlockConfig.js

[711] Remove Criminal & Tickets; Work, Credit, and Consumer; Benefits blocks

---

app/components/ui/Footer.jsx

Feedback link is going on Header instead, [#708](https://github.com/ShelterTechSF/askdarcel-web#708)

Remove feedback link from footer

---

.eslintignore
app/components/edit/CategoriesDropdown.jsx
app/components/edit/EditAddress.jsx
app/components/edit/EditCollection.jsx
app/components/edit/EditNotes.jsx
app/components/edit/EditPhones.jsx
app/components/edit/EditSidebar.jsx
app/components/edit/MultiSelectDropdown.jsx

I just went ahead and fixed all the lint issues on all the Edit components. The diff probably looks less scary when you ignore whitespace changes. I did some basic testing locally to make sure that the app still seems to function.

Fix lint on the remaining Edit components.

---

app/pages/OrganizationEditPage.jsx

Before this change, on the Organization Edit Page, deactivating a
service would navigate away, causing any other pending changes to be
thrown away.
After the change, deactivating a service, will remove the service from
the local state without navigating away.

Deactivating service does not navigate away (#381)

---

app/components/edit/EditCollection.jsx
app/components/edit/EditSchedule.jsx
app/components/edit/EditSidebar.jsx
app/components/edit/MultiSelectDropdown.jsx
app/components/edit/ProvidedService.jsx
app/pages/OrganizationEditPage.jsx
app/utils/index.js

I got a little tired of the console warnings on the Edit page, so I went ahead and fixed all the ones that I encountered. This should make it a bit easier to develop, since the console won't be cluttered with warnings.

Fix browser console warnings on Edit page.

---

app/components/listing/ActionSidebar.jsx
app/components/listing/MobileActionBar.jsx
app/utils/ResourceActions.js

Noticed that after creating a resource without a telephone number, it was throwing an error when trying to display the resource. This is a simple fix for that error.
Before:
After:

fix error on resource display when no telephone

---

.eslintignore
.eslintrc.js
app/components/listing/Notes.jsx
app/components/listing/ResourceInfos.jsx
app/pages/OrganizationListingPage.jsx

As the title says. I also made a few minor changes to the ResourceInfos file to remove the `if (!foo) return null;` guards and pushed that up higher in the component tree, since I'd argue that it's up to the parent to handle the null cases.

Fix lint on listing pages.

---

app/pages/OrganizationEditPage.jsx

Look at #638 for more details
Fix: now removing a service that was just added (but hasn't saved) makes that service disappear. Also reworded the confirmation prompt to refer to service instead of resource

638 - fix edit service bug

---

app/components/search/CategoriesRefinementList.jsx
app/components/search/EligibilitiesRefinementList.jsx
app/styles/components/_search-result-table.scss
app/styles/st-base/_forms.scss

the categoriesRefinementList and the eligiblitiesRefinementList can pretty easily be collapsed into one file/component, but i just wanted to complete this task and perhaps refactor the two at a later time

809 gray out spurious refinements

---

.eslintignore
app/components/layout/CategoryItem.jsx
app/components/layout/CategoryList.jsx
app/components/layout/FindHeader.jsx
app/components/layout/OrganizationCard.jsx
app/components/layout/ServiceCard.jsx
app/components/maps/MapOfLocations.jsx

I fixed up the lint errors on files under app/components/layouts as well as got rid of a bunch of unused, commented out references to RelativeOpeningTime.

Fix lint on app/components/layouts

---

app/components/listing/Services.jsx

801 - add space between text and actual url

---

app/components/listing/DetailedHours.jsx
app/components/listing/Services.jsx
app/utils/RecurringSchedule/models.js
app/utils/index.js

This one is relatively straightforward compared to some of my recent PRs. This updates the `<DetailedHours>` component, which is used on the Resource show page, to use the new RecurringSchedule data model. I was able to simplify the component by pushing the conditionals down further into the component, which merges together most of the HTML structure and conditionalizes just the text content.
I was also able to remove a bunch of now unused time-related helper function from utils/index.js.

Update DetailedHours to use new time helpers

---

package-lock.json
testcafe/editResource.js
testcafe/pages/EditPage.js
testcafe/pages/ResourcePage.js

Issues #432,#435: Test add/mod/del resource note

---

testcafe/newResource.js
testcafe/pages/ResourcePage.js

confirms
- website
- email
- description
- phone
There is a bug with adding a note for a new resource
Relates to #427 
Relates to https://github.com/ShelterTechSF/askdarcel-api/issues/449

Confirm adding resource fields

---

.eslintignore
app/components/ui/Accordion/Accordion.jsx
app/components/ui/Accordion/AccordionItem.jsx
app/components/ui/LandingPageEligibilityBlock.jsx
app/components/ui/WhiteLabel.jsx

Note that this is probably easier to review with whitespace diffs ignored.
This should be the last of the lint fixes for files that are actually used in production. Everything else left in the `.eslintignore` is either the old admin pages or debugging pages.

Fix lint on components/ui files.

---

package-lock.json
package.json
travis-testcafe.sh

Like I mentioned in https://github.com/ShelterTechSF/askdarcel-web/pull/855#issuecomment-529241642, the latest TestCafe fixes the text input bug with text getting input in reverse order. I confirmed that this fixes the issue for me locally. I also bumped up the version of Chrome we're testing against from 73 to 76, since apparently the bug only started showing up in Chrome 75.

Upgrade TestCafe to fix text input bug.

---

testcafe/editResource.js
testcafe/newResource.js
testcafe/pages/EditPage.js
testcafe/pages/ResourcePage.js
testcafe/pages/ServicePage.js
testcafe/service.js

- name
- description
- address
- phone
- note
Relates to #420

Issue #420: Verify service data

---

app/pages/HomePage/components/GuideList/GuideList.jsx
package-lock.json
package.json

added typeform popup to the guided pathway links

add typeform integration; fix lint

---

app/pages/HomePage/components/GuideList/GuideList.jsx
app/styles/utils/_helpers.scss

once all the typeform links are available and the forms are ready, we can merge this PR

update links to available typeforms

---

package-lock.json
package.json
testing/mocha.js

This bumps a couple of dev dependencies that are super old so that we pick up security updates and hopefully other nice improvements.

Bump dev dependencies

---

app/components/listing/ResourceInfos.jsx
app/components/listing/TableOfContactInfo.jsx
app/pages/OrganizationListingPage.jsx

Also made a minor change with a heading

Fixed issue for making phone numbers clickable

---

travis-testcafe.sh

Trying to debug why Travis CI tests are all currently failing.

Add more error checking for Travis CI failures and fix broken Travis Postgres error

---

app/components/ui/Banner/Banner.jsx
app/components/ui/Banner/Banner.scss
app/styles/utils/_colors.scss

Update covid banner copy & design

---

app/components/ui/Banner/Banner.jsx
app/components/ui/Banner/Banner.scss
app/pages/Covid/Covid.jsx
app/pages/Covid/Covid.scss
app/pages/HomePage/components/GuideList/GuideList.jsx
app/pages/HomePage/components/GuideList/GuideList.scss
app/styles/utils/_helpers.scss
package-lock.json
package.json

- Increased accesibilty for the cards by adding more visible buttons and a border
- Made the banner and font sizes on the covid page smaller on mobile
- removed the intercom logo on mobile
- added padding to the google doc embed

Updated guide cards, covid page for covid launch

---

app/pages/Covid/Covid.jsx

Text changes to COVID page subheader

---

app/pages/Covid/Covid.jsx
app/pages/Covid/Covid.scss

added blue border to embed and made width smaller

Made more mobile friendly

---

app/pages/HomePage/HomePage.jsx
app/pages/HomePage/components/GuideList/GuideList.jsx
app/pages/HomePage/components/HomePageHero/HomePageHero.scss

- New wording of homepage title
- New wording for food content

Adjust wording of pages based on feedback in staging

---

app/components/edit/EditSidebar.jsx

after clicking service on sidebar it'll scroll to that service on  organization edit page

ui-scroll-effect

---

app/pages/OrganizationEditPage.jsx

also removed conditional which already existed

create resource without physical address if hasLocation is false

---

app/components/ui/Modal/ServiceDiscoveryModal/ServiceDiscoveryModal.jsx
app/pages/HomePage/components/GuideList/GuideList.jsx
app/pages/ServiceDiscoveryResults/ClearAllFilters.jsx
app/pages/ServiceDiscoveryResults/EligibilitiesListFilter.jsx
app/pages/ServiceDiscoveryResults/OpenNowFilter.jsx
app/pages/ServiceDiscoveryResults/RefinementListFilter.jsx
app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.jsx

This PR continues where https://github.com/ShelterTechSF/askdarcel-web/pull/956 left off. In this PR I hook the `Hygiene` guide up to the new pathway and do some work to support both eligibilities and subcategories. There's a little bit of clean up of the search logic, but still plenty more clean up to be done here.

Hook up Hygiene Pathway

---

app/components/ui/Banner/Banner.jsx

Update covid banner text

---

app/components/ui/Banner/Banner.jsx

This update the COVID-19 banner with the latest information about vaccine eligibility starting March 15th.

Update COVID-19 banner with latest information.

---

app/index.html

@richardxia formatted the scripts to 1 line

Add Google Tag Manager

---

app/components/edit/EditAddress.jsx
app/components/edit/EditAddress.module.scss
app/components/listing/ActionSidebar.jsx
app/components/listing/MobileActionBar.jsx
app/init.tsx
app/pages/OrganizationEditPage.jsx
package-lock.json
package.json
testcafe/editResource.js
testcafe/newResource.js
testcafe/pages/EditPage.js

Implements https://app.clubhouse.io/sheltertech/story/1445/add-new-address-and-edit-address-modals
Figma design: https://www.figma.com/file/tBRClGsxYN9m6ZvL2STB6t/WIP-Edit-Redesign---Unscheduled?node-id=2839%3A134
This replaces the old address forms from the Edit page with the new modal-based ones. See  for the designs that this is roughly following, though this PR is focused just on the edit address forms for Organizations, and not the related form for Services or any of the other changes.
This ended up being a pretty substantial rewrite of the edit address forms, since it switches away from the `editCollectionHOC` higher-order component that we had for automatically generating components for editing collections of objects to a new set of components.
A few of the more notable changes …

New and edit address modal forms

---

app/components/ui/Banner/Banner.jsx

Im not a professional designer but I paid attention to the previous format of the bold points, the visual hierarchy and line breaks. This design was to my best judgement and open to suggestions and changes.
Desktop View
Mobile View

Banner change

---

app/utils/whitelabel.ts

Patch to fix bug where SF service guide staging ENV shows askdarcel logo

Fix sfserviceguide whitelabel staging bug.

---

app/components/listing/feedback/FeedbackForm.tsx
app/components/listing/feedback/FeedbackSteps.tsx
app/components/listing/feedback/constants.ts

Refs #1175.
This migrates the Feedback components to TypeScript. There are a few minor, non-type changes that I made in order to get everything to pass type checking, but they shouldn't cause any functional changes to the app.

Migrate Feedback components to TypeScript.

---

app/components/search/SearchResults/SearchResults.jsx
app/components/search/SearchResults/SearchResults.module.scss

From Figma: https://www.figma.com/file/HUTUyVuJf8lctj5fAFIY32/UCSF?node-id=5946%3A3675#302001402

Emphasize ucsf sidelinks

---

.eslintrc.js
app/components/listing/__tests__/RelativeOpeningTimes.spec.tsx
app/pages/debug/ListingDemoPage.tsx

Refs #1175.
This migrates a couple of testing and debug-only files to TypeScript. It was honestly kind of difficult to figure out the exact types, since they're pretty dynamic, so I'm glad that I did this because now it's easier to understand the types of the test data here.

Migrate ListingDemoPage to TypeScript.

---

.eslintrc.js
app/App.tsx
app/components/listing/RelativeOpeningTime.tsx
app/components/search/SearchResults/SearchResults.jsx
app/components/search/Sidebar/Sidebar.tsx
app/components/ucsf/RefinementLists/EligibilityRefinements.tsx
app/hooks/APIHooks.js
app/pages/ServiceDiscoveryForm/ServiceDiscoveryForm.tsx
app/pages/UcsfDiscoveryForm/UcsfDiscoveryForm.tsx
package-lock.json
package.json

Note: This PR is not quite ready to merge yet, since there's one remaining rule violation that I wasn't sure what the right fix is. I'm going to leave an inline comment in the diff on the block of code in question.
There are a few rules that we have to follow when using React Hooks, documented at https://reactjs.org/docs/hooks-rules.html. While working on something else, I realized that we were violating some of these rules, in particular, the rule that hooks cannot be conditionally executed. This means that every component that calls a hook must do so unconditionally; you should not call them from within `if` blocks, `for` loops, and you also can't do an early return before all hooks have executed.
If you're interested in _why_ this rule exists, this article I read several years ago …

Fix React Rules of Hooks violations

---

app/components/ui/Translate.tsx
app/utils/whitelabel.ts

* Vietnamese (vi), Arabic (ar), Russian (ru)
* Enable setting language codes per whitelabel with `enabledTranslations` (to replace `enableTranslation` bool)

Enable more languages for Our415 whitelabel

---

app/components/ui/HamburgerMenu.module.scss
app/components/ui/HamburgerMenu.tsx
app/components/ui/Navigation.module.scss
app/components/ui/Navigation.tsx
app/styles/utils/_layoututils.scss
app/utils/whitelabel.ts

https://www.loom.com/share/b6d4a53274934960b01bd8209d9579ea

Add report street crisis button to navigation.

---

app/components/search/SearchResults/SearchResults.jsx
app/pages/Pdf/ServicePdfPage.tsx
app/pages/Pdf/styles.module.scss

We are now going to generate PDFs for all UCSF services. I have set up usage alerts in a slack channel #google-cloud-alerts and will be monitoring usage closely. There is also a daily cap. I do not think UCSF will get too close to our limits for now.

Use PDF generation for all PDFs. Small UI improvements

---

app/models/BreakingNewsArticle.ts
app/models/index.ts
app/pages/EditBreakingNewsPage.scss
app/pages/EditBreakingNewsPage.tsx
package-lock.json

Adding a few tweaks to get this ready to be merged in. Creating a PR to give @dfloo and team a better record of changes. This PR: 
- undoes outdated package-lock changes
- removes console log statements
- adds new URL field to reflect change in data model
- splits adding a breaking news item and saving it into two steps
- subsequently, allows deletion of a news item that has not been saved
NOTE: I also merged Master into the original [1161-edit-breaking-news-page](https://github.com/ShelterTechSF/askdarcel-web/tree/1161-edit-breaking-news-page) branch, so the new NewsArticle model, which was created as part of a separate PR, is already there, in the `models/Meta.ts`

1161 breaking news fixes

---

app/components/search/Header/Header.tsx
app/components/search/SearchResults/SearchResults.jsx
app/pages/Pdf/ServicePdfPage.tsx
app/pages/SearchResultsPage/SearchResultsPage.tsx

API PR here: https://github.com/ShelterTechSF/askdarcel-api/pull/686

Complete search translation

---

app/components/edit/FormTextArea.tsx
app/components/edit/ProvidedService.tsx
app/models/Organization.ts
app/models/Service.ts
app/pages/OrganizationEditPage.scss
app/pages/OrganizationEditPage.tsx

1266 Add internal note field to service and resource on the Edit Page

---

docker/tiller/templates/askdarcel-web.conf.erb
webpack.config.js

This reverts commit 64da16a3905d7a867f9d868cba99f23cbcf0df15.

Revert "feat: add v2 route for separate backend service config (#1285)"

---

app/components/edit/ProvidedService.tsx
app/models/Service.ts

Adding Richard for reference, but going to go ahead and merge this in

Add Short Description field to Service

---

app/components/edit/EditNote.tsx
app/components/edit/EditNotes.tsx
app/components/edit/ProvidedService.tsx
app/pages/OrganizationEditPage.tsx

This initially started as a project to remove direct state mutations in the Notes component but then I eventually decided to refactor the entire Notes component given a few bad practices I observed, not to mention some confusing code. There isn't a time crunch to get this merged in, so I think it's best to leave it open until @richardxia is back and has a chance to review it, given his deep familiarity with the OrganizationEditPage architecture and our codebase in general

1294 refactor notes component

---

app/components/search/SearchMap/SearchMap.scss
app/components/search/SearchMap/SearchMap.tsx
app/components/search/SearchResults/SearchResults.tsx
app/components/ui/inline/Button/Button.module.scss
app/pages/SearchResultsPage/SearchResultsPage.tsx
app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.tsx

Refs #1331 . The map accepts user location as default. Upon moving and clicking the "search this area" button the user location is then overridden by map center coords.
_Note: for some reason the desktop screenshot shows the top button border looking weird. This seems to be a fluke of the screenshot rather than how the button actually looks_

1331 Implement search by location

---

app/components/utils/ProtectedRoute.tsx
app/pages/AuthInterstitial.tsx

Merging in to test why login usually fails in prod

Add logging to debug prod login issue

---

app/components/utils/ProtectedRoute.tsx
app/pages/AuthInterstitial.tsx
app/utils/AuthService.ts

see my slack message regarding this PR. it is an attempt to fix the prod auth bug, which affects chrome but not firefox, weirdly enough. i plan to deploy this today in the hopes that it will fix the prod env.

Create state token on client in attempt to fix prod auth bug

---

app/components/search/SearchResults/SearchResults.tsx
app/components/ui/BookmarkModal/BookmarkModal.tsx
app/components/ui/BookmarksMenu/BookmarksMenu.tsx
app/models/Bookmark.ts
app/models/User.ts
app/pages/NavigatorDashboard/NavigatorDashboard.tsx
webpack.config.js

Refs #1349.
This replaces all the placeholder data related to bookmarks with actual API calls to the newly added Bookmarks and Folders APIs. There are a few mismatches between the existing frontend code and the backend APIs that we actually ended up implementing. For expediency, we mostly just work around gaps or omissions from the backend APIs, but ideally these should be addressed in the future.
Two recurring issues are that the Bookmarks API does not have a name field, and it does not return the `updated_at` field. The former doesn't even exist in the database table definition, but the latter is just an omission. Some of the changes in this commit work around the lack of these fields, including making an API request to the bookmarked service or resource to grab its name.
There are some …

Hook up bookmarks APIs.

---

app/Router.tsx
app/components/utils/PublicRoute.tsx
app/pages/AuthInterstitial.tsx

Fixes #1370.
This was the original intent of the Navigator Dashboard, but was not configured this way yet.

Have Navigator Dashboard replace Home Page when logged in.

---

app/components/ui/Navigation.tsx

There is a new URL that this button should point to.

Update Report Street Crisis URL.

---

app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.tsx

use v2 endpoint, remove extra nested "category" property

Switch over to v2 endpoint for categories
